## Task #1 - Data Cleaning Challenge on Sales Data

In [7]:
pd.pivot_table(data=insurance_data, values="charges", index="region", columns=["sex","children"]).round()

sex         female                                                  male  \
children         0        1        2        3        4        5        0
region
northeast   9790.0  17125.0  14523.0  13730.0  14542.0      NaN  13390.0
northwest  12584.0  11119.0  13128.0  13431.0  11024.0   8966.0   9813.0
southeast  14862.0   9870.0  11766.0  19723.0  18267.0   9924.0  13792.0
southwest  10150.0  10842.0  16230.0   8439.0  10946.0  10024.0  13727.0

sex
children         1        2        3        4        5
region
northeast  15474.0  12318.0  14935.0  14442.0   6979.0
northwest   9515.0  13763.0  22971.0  11508.0      NaN
southeast  17425.0  18648.0  17102.0   8727.0  10307.0
southwest   9971.0  18876.0  12072.0  17924.0   6865.0

### 3.1 Find out the average insurance charges based on Region

In [11]:
insurance_data.groupby(by=["region"])["charges"].mean().sort_values(ascending=False).round(2)

region
southeast    14735.41
northeast    13406.38
northwest    12417.58
southwest    12346.94
Name: charges, dtype: float64

In [15]:
insurance_data.groupby(by=["region","sex"])["charges"].agg(func=["mean", "min","max","sum"]).round()

                     mean     min      max        sum
region    sex
northeast female  12953.0  2196.0  58571.0  2085466.0
          male    13854.0  1695.0  48549.0  2258203.0
northwest female  12480.0  2117.0  55135.0  2046699.0
          male    12354.0  1621.0  60021.0  1989013.0
southeast female  13500.0  1608.0  63770.0  2362442.0
          male    15880.0  1122.0  62593.0  3001248.0
southwest female  11274.0  1728.0  48824.0  1826455.0
          male    13413.0  1242.0  52591.0  2186300.0

In [17]:
insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

#### 4.1 Find out the numbers of smokers and non-smokers based on region

In [19]:
pd.crosstab(index=insurance_data["region"], columns=insurance_data["smoker"], margins=True)

smoker       no  yes   All
region
northeast   257   67   324
northwest   267   58   325
southeast   273   91   364
southwest   267   58   325
All        1064  274  1338

In [3]:
import pandas as pd

In [4]:
sales_data_2017 = pd.read_csv("Sales_Transactions_2017.csv")
sales_data_2018 = pd.read_csv("Sales_Transactions_2018.csv")
sales_data_2019 = pd.read_csv("Sales_Transactions_2019.csv")
sales_data_edited = pd.read_csv("Sales_Transactions_Edit.csv")

In [5]:
sales_data_2017

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2019,Sal:687,BALAJI PLASTICS,DONA-VAI-9100,1,"1,730.00","1,730.00",NaN,"3,460.00"
1,1/4/2019,Sal:687,BALAJI PLASTICS,SMART BOUL(48),1,"1,730.00","1,730.00",NaN,NaN
2,1/4/2019,Sal:688,BALAJI PLASTICS,Vishnu Ice,110,18.5,"2,035.00",NaN,"2,035.00"
3,,,28/3,,0,0,,,
4,1/4/2019,Sal:689,BALAJI PLASTICS,100LEAF -SP,3,585,"1,755.00",NaN,"1,755.00"
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [6]:
sales_data_2018

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2018,Sal:146,TP13,SILVER POUCH 9*12,50,85,"4,250.00",NaN,"66,724.00"
1,1/4/2018,Sal:146,TP13,RUBBER,5,290,"1,450.00",NaN,NaN
2,1/4/2018,Sal:146,TP13,DURGA 10*12 Blue,"1,600.00",5.5,"8,800.00",NaN,NaN
3,1/4/2018,Sal:146,TP13,DURGA 13*16 BLUE,400,11,"4,400.00",NaN,NaN
4,1/4/2018,Sal:146,TP13,10*12 SARAS-NAT,600,8.1,"4,860.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
44735,31/03/2019,Sal:9610,HAMPI FOODS,SPOON SOOFY,200,40,"8,000.00",NaN,NaN
44736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44738,NaN,Total,NaN,NaN,"666,056.00","1,067,808.80","10,796,991.30","29,999.00","10,787,647.30"
44739,NaN,Total,NaN,NaN,"7,097,803.00","10,024,197.00","117,897,671.80","720,204.00","117,427,983.80"

In [7]:
sales_data_2019

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
47285,31/03/2018,Sal:10042,Vkp,10*10 SHEET,25,137,"3,425.00",NaN,"3,425.00"
47286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47288,NaN,Total,NaN,NaN,"607,734.60","669,300.49","9,953,816.13","106,607.00","9,868,583.13"
47289,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71"

In [8]:
sales_data_edited

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
95557,12/9/2019,4265,TP13,SPOON MED M.W,20,11.0
95558,12/9/2019,4266,K.SRIHARI,SMART BOUL(48),1,1830.0
95559,12/9/2019,4267,SMS,SMARTBOUL GLA(4000),1,1520.0
95560,12/9/2019,4268,ANILFANCY,RR WINEGLASS,100,20.0
95561,12/9/2019,4268,ANILFANCY,RR WATER GLASS,100,20.0

In [9]:
sales_data_edited.dtypes

Date        object
Voucher      int64
Party       object
Product     object
Qty          int64
Rate       float64
dtype: object

In [10]:
sales_all_data = pd.concat(objs=[sales_data_2017,sales_data_2018, sales_data_2019])
sales_all_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2019,Sal:687,BALAJI PLASTICS,DONA-VAI-9100,1,"1,730.00","1,730.00",NaN,"3,460.00"
1,1/4/2019,Sal:687,BALAJI PLASTICS,SMART BOUL(48),1,"1,730.00","1,730.00",NaN,NaN
2,1/4/2019,Sal:688,BALAJI PLASTICS,Vishnu Ice,110,18.5,"2,035.00",NaN,"2,035.00"
3,,,28/3,,0,0,,,
4,1/4/2019,Sal:689,BALAJI PLASTICS,100LEAF -SP,3,585,"1,755.00",NaN,"1,755.00"
...,...,...,...,...,...,...,...,...,...
47285,31/03/2018,Sal:10042,Vkp,10*10 SHEET,25,137,"3,425.00",NaN,"3,425.00"
47286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47288,NaN,Total,NaN,NaN,"607,734.60","669,300.49","9,953,816.13","106,607.00","9,868,583.13"
47289,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71"

In [11]:
sales_all_data.dtypes

Date              object
Voucher           object
Party             object
Product           object
Qty               object
Rate              object
Gross             object
Disc              object
Voucher Amount    object
dtype: object

In [12]:
sales_all_data.isna().sum()

Date               12591
Voucher            12557
Party                 40
Product            12591
Qty                12557
Rate               12558
Gross              12558
Disc              105609
Voucher Amount     83646
dtype: int64

In [13]:
sales_all_data.shape

(111206, 9)

In [15]:
sales_all_data.drop_duplicates(inplace=True)
sales_all_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2019,Sal:687,BALAJI PLASTICS,DONA-VAI-9100,1,"1,730.00","1,730.00",NaN,"3,460.00"
1,1/4/2019,Sal:687,BALAJI PLASTICS,SMART BOUL(48),1,"1,730.00","1,730.00",NaN,NaN
2,1/4/2019,Sal:688,BALAJI PLASTICS,Vishnu Ice,110,18.5,"2,035.00",NaN,"2,035.00"
3,,,28/3,,0,0,,,
4,1/4/2019,Sal:689,BALAJI PLASTICS,100LEAF -SP,3,585,"1,755.00",NaN,"1,755.00"
...,...,...,...,...,...,...,...,...,...
47281,31/03/2018,Sal:10041,HARITHA BEACH RESOR,APPLE WATER,10,25,250,NaN,NaN
47283,31/03/2018,Sal:10041,HARITHA BEACH RESOR,BLACK DOG-350ML,10,26,260,NaN,NaN
47285,31/03/2018,Sal:10042,Vkp,10*10 SHEET,25,137,"3,425.00",NaN,"3,425.00"
47288,NaN,Total,NaN,NaN,"607,734.60","669,300.49","9,953,816.13","106,607.00","9,868,583.13"
47289,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71"

In [16]:
sales_all_data.isna().sum()

Date                204
Voucher             170
Party                35
Product             204
Qty                 170
Rate                171
Gross               171
Disc              92951
Voucher Amount    70984
dtype: int64

In [20]:
valid_sales_all_data = sales_all_data[sales_all_data["Date"].notna() & 
    sales_all_data["Voucher"].notna()  & 
    sales_all_data["Party"].notna() &
    sales_all_data["Product"].notna()  & 
    sales_all_data["Qty"].notna()  & 
    sales_all_data["Rate"].notna()]

valid_sales_all_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2019,Sal:687,BALAJI PLASTICS,DONA-VAI-9100,1,"1,730.00","1,730.00",NaN,"3,460.00"
1,1/4/2019,Sal:687,BALAJI PLASTICS,SMART BOUL(48),1,"1,730.00","1,730.00",NaN,NaN
2,1/4/2019,Sal:688,BALAJI PLASTICS,Vishnu Ice,110,18.5,"2,035.00",NaN,"2,035.00"
3,,,28/3,,0,0,,,
4,1/4/2019,Sal:689,BALAJI PLASTICS,100LEAF -SP,3,585,"1,755.00",NaN,"1,755.00"
...,...,...,...,...,...,...,...,...,...
47277,31/03/2018,Sal:10041,HARITHA BEACH RESOR,PAPER TEA 150ML,10,40,400,NaN,NaN
47279,31/03/2018,Sal:10041,HARITHA BEACH RESOR,PRINT 13*16,2,120,240,NaN,NaN
47281,31/03/2018,Sal:10041,HARITHA BEACH RESOR,APPLE WATER,10,25,250,NaN,NaN
47283,31/03/2018,Sal:10041,HARITHA BEACH RESOR,BLACK DOG-350ML,10,26,260,NaN,NaN
47285,31/03/2018,Sal:10042,Vkp,10*10 SHEET,25,137,"3,425.00",NaN,"3,425.00"

In [21]:
valid_sales_all_data.isna().sum()

Date                  0
Voucher               0
Party                 0
Product               0
Qty                   0
Rate                  0
Gross                 0
Disc              92780
Voucher Amount    70813
dtype: int64

In [22]:
# valid_sales_all_data = valid_sales_all_data.drop(columns=["Gross", "Disc", "Voucher Amount"])
valid_sales_all_data = valid_sales_all_data[["Date","Voucher","Party","Product","Qty","Rate"]]
valid_sales_all_data

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2019,Sal:687,BALAJI PLASTICS,DONA-VAI-9100,1,"1,730.00"
1,1/4/2019,Sal:687,BALAJI PLASTICS,SMART BOUL(48),1,"1,730.00"
2,1/4/2019,Sal:688,BALAJI PLASTICS,Vishnu Ice,110,18.5
3,,,28/3,,0,0
4,1/4/2019,Sal:689,BALAJI PLASTICS,100LEAF -SP,3,585
...,...,...,...,...,...,...
47277,31/03/2018,Sal:10041,HARITHA BEACH RESOR,PAPER TEA 150ML,10,40
47279,31/03/2018,Sal:10041,HARITHA BEACH RESOR,PRINT 13*16,2,120
47281,31/03/2018,Sal:10041,HARITHA BEACH RESOR,APPLE WATER,10,25
47283,31/03/2018,Sal:10041,HARITHA BEACH RESOR,BLACK DOG-350ML,10,26
47285,31/03/2018,Sal:10042,Vkp,10*10 SHEET,25,137

In [23]:
valid_sales_all_data.isna().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       0
dtype: int64

In [24]:
valid_sales_all_data.shape

(96419, 6)

In [25]:
valid_sales_all_data.dtypes

Date       object
Voucher    object
Party      object
Product    object
Qty        object
Rate       object
dtype: object

In [26]:
valid_sales_all_data = valid_sales_all_data.copy()

valid_sales_all_data["Voucher"] = (
    valid_sales_all_data["Voucher"]
    .astype(str)
    .str.replace("Sal:", "", regex=False)
)

valid_sales_all_data

             Date Voucher                Party          Product  Qty      Rate
0        1/4/2019     687      BALAJI PLASTICS    DONA-VAI-9100    1  1,730.00
1        1/4/2019     687      BALAJI PLASTICS   SMART BOUL(48)    1  1,730.00
2        1/4/2019     688      BALAJI PLASTICS       Vishnu Ice  110      18.5
3                                         28/3                     0         0
4        1/4/2019     689      BALAJI PLASTICS      100LEAF -SP    3       585
...           ...     ...                  ...              ...  ...       ...
47277  31/03/2018   10041  HARITHA BEACH RESOR  PAPER TEA 150ML   10        40
47279  31/03/2018   10041  HARITHA BEACH RESOR      PRINT 13*16    2       120
47281  31/03/2018   10041  HARITHA BEACH RESOR      APPLE WATER   10        25
47283  31/03/2018   10041  HARITHA BEACH RESOR  BLACK DOG-350ML   10        26
47285  31/03/2018   10042                  Vkp      10*10 SHEET   25       137

[96419 rows x 6 columns]

In [27]:
valid_sales_all_data.isna().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       0
dtype: int64

In [28]:
valid_sales_all_data.dtypes

Date       object
Voucher    object
Party      object
Product    object
Qty        object
Rate       object
dtype: object

In [29]:
valid_sales_all_data = valid_sales_all_data.replace(r'^\s*$', pd.NA, regex=True)
valid_sales_all_data = valid_sales_all_data.dropna().reset_index(drop=True)

valid_sales_all_data

             Date Voucher                Party          Product  Qty      Rate
0        1/4/2019     687      BALAJI PLASTICS    DONA-VAI-9100    1  1,730.00
1        1/4/2019     687      BALAJI PLASTICS   SMART BOUL(48)    1  1,730.00
2        1/4/2019     688      BALAJI PLASTICS       Vishnu Ice  110      18.5
3        1/4/2019     689      BALAJI PLASTICS      100LEAF -SP    3       585
4        2/4/2019       1                  Tvr    BAHUBALI WINE  110        25
...           ...     ...                  ...              ...  ...       ...
95281  31/03/2018   10041  HARITHA BEACH RESOR  PAPER TEA 150ML   10        40
95282  31/03/2018   10041  HARITHA BEACH RESOR      PRINT 13*16    2       120
95283  31/03/2018   10041  HARITHA BEACH RESOR      APPLE WATER   10        25
95284  31/03/2018   10041  HARITHA BEACH RESOR  BLACK DOG-350ML   10        26
95285  31/03/2018   10042                  Vkp      10*10 SHEET   25       137

[95286 rows x 6 columns]

In [30]:
valid_sales_all_data["Voucher"] = valid_sales_all_data["Voucher"].str.replace("Sal:","").astype(int)

In [31]:
valid_sales_all_data.dtypes

Date       object
Voucher     int64
Party      object
Product    object
Qty        object
Rate       object
dtype: object

In [32]:
valid_sales_all_data["Qty"] = pd.to_numeric(
    valid_sales_all_data["Qty"].astype(str).str.replace(",", "", regex=False),
    errors="coerce"
).astype(int)

In [34]:
valid_sales_all_data.dtypes

Date       object
Voucher     int64
Party      object
Product    object
Qty         int64
Rate       object
dtype: object

In [35]:
valid_sales_all_data

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2019,687,BALAJI PLASTICS,DONA-VAI-9100,1,"1,730.00"
1,1/4/2019,687,BALAJI PLASTICS,SMART BOUL(48),1,"1,730.00"
2,1/4/2019,688,BALAJI PLASTICS,Vishnu Ice,110,18.5
3,1/4/2019,689,BALAJI PLASTICS,100LEAF -SP,3,585
4,2/4/2019,1,Tvr,BAHUBALI WINE,110,25
...,...,...,...,...,...,...
95281,31/03/2018,10041,HARITHA BEACH RESOR,PAPER TEA 150ML,10,40
95282,31/03/2018,10041,HARITHA BEACH RESOR,PRINT 13*16,2,120
95283,31/03/2018,10041,HARITHA BEACH RESOR,APPLE WATER,10,25
95284,31/03/2018,10041,HARITHA BEACH RESOR,BLACK DOG-350ML,10,26
95285,31/03/2018,10042,Vkp,10*10 SHEET,25,137

In [36]:
valid_sales_all_data["Rate"] = pd.to_numeric(
    valid_sales_all_data["Rate"].astype(str).str.replace(",", "", regex=False),
    errors="coerce"
).astype(float)

In [37]:
valid_sales_all_data.dtypes

Date        object
Voucher      int64
Party       object
Product     object
Qty          int64
Rate       float64
dtype: object

In [38]:
valid_sales_all_data

             Date  Voucher                Party          Product  Qty    Rate
0        1/4/2019      687      BALAJI PLASTICS    DONA-VAI-9100    1  1730.0
1        1/4/2019      687      BALAJI PLASTICS   SMART BOUL(48)    1  1730.0
2        1/4/2019      688      BALAJI PLASTICS       Vishnu Ice  110    18.5
3        1/4/2019      689      BALAJI PLASTICS      100LEAF -SP    3   585.0
4        2/4/2019        1                  Tvr    BAHUBALI WINE  110    25.0
...           ...      ...                  ...              ...  ...     ...
95281  31/03/2018    10041  HARITHA BEACH RESOR  PAPER TEA 150ML   10    40.0
95282  31/03/2018    10041  HARITHA BEACH RESOR      PRINT 13*16    2   120.0
95283  31/03/2018    10041  HARITHA BEACH RESOR      APPLE WATER   10    25.0
95284  31/03/2018    10041  HARITHA BEACH RESOR  BLACK DOG-350ML   10    26.0
95285  31/03/2018    10042                  Vkp      10*10 SHEET   25   137.0

[95286 rows x 6 columns]

In [39]:
valid_sales_all_data.isna().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       0
dtype: int64

In [40]:
valid_sales_all_data["Date"] = pd.to_datetime(
    valid_sales_all_data["Date"],
    format="%d/%m/%Y",
    errors="coerce"
)

In [41]:
valid_sales_all_data

            Date  Voucher                Party          Product  Qty    Rate
0     2019-04-01      687      BALAJI PLASTICS    DONA-VAI-9100    1  1730.0
1     2019-04-01      687      BALAJI PLASTICS   SMART BOUL(48)    1  1730.0
2     2019-04-01      688      BALAJI PLASTICS       Vishnu Ice  110    18.5
3     2019-04-01      689      BALAJI PLASTICS      100LEAF -SP    3   585.0
4     2019-04-02        1                  Tvr    BAHUBALI WINE  110    25.0
...          ...      ...                  ...              ...  ...     ...
95281 2018-03-31    10041  HARITHA BEACH RESOR  PAPER TEA 150ML   10    40.0
95282 2018-03-31    10041  HARITHA BEACH RESOR      PRINT 13*16    2   120.0
95283 2018-03-31    10041  HARITHA BEACH RESOR      APPLE WATER   10    25.0
95284 2018-03-31    10041  HARITHA BEACH RESOR  BLACK DOG-350ML   10    26.0
95285 2018-03-31    10042                  Vkp      10*10 SHEET   25   137.0

[95286 rows x 6 columns]

In [42]:
print(valid_sales_all_data.dtypes)

Date       datetime64[ns]
Voucher             int64
Party              object
Product            object
Qty                 int64
Rate              float64
dtype: object

## Task #2 - Merge Function 1 Example

- **merge()** is used to combine two DataFrames based on a common column (key), similar to SQL JOIN operations.

In [2]:
employee_data = pd.read_csv("employees.csv")

employee_data

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-SEP-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,6000,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-MAR-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,2800,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,2600,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,2500,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,5800,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,3200,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,2700,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,2400,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,2200,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,3300,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,2800,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,2500,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,2100,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,3300,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,2900,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,2400,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500,-,123,50

In [3]:
department_data = pd.read_csv("departments.csv")

department_data

    DEPARTMENT_ID       DEPARTMENT_NAME MANAGER_ID  LOCATION_ID
0              10        Administration        200         1700
1              20             Marketing        201         1800
2              30            Purchasing        114         1700
3              40       Human Resources        203         2400
4              50              Shipping        121         1500
5              60                    IT        103         1400
6              70      Public Relations        204         2700
7              80                 Sales        145         2500
8              90             Executive        100         1700
9             100               Finance        108         1700
10            110            Accounting        205         1700
11            120              Treasury         -          1700
12            130         Corporate Tax         -          1700
13            140    Control And Credit         -          1700
14            150  Shareholder Services         -          1700
15            160              Benefits         -          1700
16            170         Manufacturing         -          1700
17            180          Construction         -          1700
18            190           Contracting         -          1700
19            200            Operations         -          1700
20            210            IT Support         -          1700
21            220                   NOC         -          1700
22            230           IT Helpdesk         -          1700
23            240      Government Sales         -          1700
24            250          Retail Sales         -          1700
25            260            Recruiting         -          1700
26            270               Payroll         -          1700

### 2.1 Inner Join

- Returns only matching records from both DataFrames.

In [42]:
result = pd.merge(
        employee_data, 
        department_data, 
        on="DEPARTMENT_ID", 
        how="inner",
        suffixes=("_Employee", "_Department") # If tables has same column name then it will append suffixes
    )

result

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID_Employee,DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID_Department,LOCATION_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50,Shipping,121,1500
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50,Shipping,121,1500
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10,Administration,200,1700
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20,Marketing,201,1800
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20,Marketing,201,1800
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40,Human Resources,203,2400
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000,-,101,70,Public Relations,204,2700
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008,-,101,110,Accounting,205,1700
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,8300,-,205,110,Accounting,205,1700
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000,-,-,90,Executive,100,1700
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-SEP-05,AD_VP,17000,-,100,90,Executive,100,1700
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000,-,100,90,Executive,100,1700
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60,IT,103,1400
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,6000,-,103,60,IT,103,1400
14,105,David,Austin,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,4800,-,103,60,IT,103,1400
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,4800,-,103,60,IT,103,1400
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,4200,-,103,60,IT,103,1400
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,12008,-,101,100,Finance,108,1700
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100,Finance,108,1700
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,8200,-,108,100,Finance,108,1700
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,7700,-,108,100,Finance,108,1700
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-MAR-06,FI_ACCOUNT,7800,-,108,100,Finance,108,1700
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,6900,-,108,100,Finance,108,1700
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,11000,-,100,30,Purchasing,114,1700
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100,-,114,30,Purchasing,114,1700
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,2900,-,114,30,Purchasing,114,1700
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,2800,-,114,30,Purchasing,114,1700
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,2600,-,114,30,Purchasing,114,1700
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,2500,-,114,30,Purchasing,114,1700
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,8000,-,100,50,Shipping,121,1500
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200,-,100,50,Shipping,121,1500
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,7900,-,100,50,Shipping,121,1500
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,6500,-,100,50,Shipping,121,1500
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,5800,-,100,50,Shipping,121,1500
34,125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,3200,-,120,50,Shipping,121,1500
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,2700,-,120,50,Shipping,121,1500
36,127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,2400,-,120,50,Shipping,121,1500
37,128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,2200,-,120,50,Shipping,121,1500
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,3300,-,121,50,Shipping,121,1500
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,2800,-,121,50,Shipping,121,1500
40,131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,2500,-,121,50,Shipping,121,1500
41,132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,2100,-,121,50,Shipping,121,1500
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,3300,-,122,50,Shipping,121,1500
43,134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,2900,-,122,50,Shipping,121,1500
44,135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,2400,-,122,50,Shipping,121,1500
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200,-,122,50,Shipping,121,1500
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600,-,123,50,Shipping,121,1500
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200,-,123,50,Shipping,121,1500
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700,-,123,50,Shipping,121,1500
49,140,Joshua,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500,-,123,50,Shipping,121,1500

#### 2.1.1 - Select specific columns

In [11]:
result = pd.merge(
        employee_data, 
        department_data, 
        on="DEPARTMENT_ID", 
        how="inner"
    )[["EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "PHONE_NUMBER", "SALARY", "DEPARTMENT_NAME", "DEPARTMENT_ID"]]

result

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,SALARY,DEPARTMENT_NAME,DEPARTMENT_ID
0,198,Donald,OConnell,650.507.9833,2600,Shipping,50
1,199,Douglas,Grant,650.507.9844,2600,Shipping,50
2,200,Jennifer,Whalen,515.123.4444,4400,Administration,10
3,201,Michael,Hartstein,515.123.5555,13000,Marketing,20
4,202,Pat,Fay,603.123.6666,6000,Marketing,20
5,203,Susan,Mavris,515.123.7777,6500,Human Resources,40
6,204,Hermann,Baer,515.123.8888,10000,Public Relations,70
7,205,Shelley,Higgins,515.123.8080,12008,Accounting,110
8,206,William,Gietz,515.123.8181,8300,Accounting,110
9,100,Steven,King,515.123.4567,24000,Executive,90
10,101,Neena,Kochhar,515.123.4568,17000,Executive,90
11,102,Lex,De Haan,515.123.4569,17000,Executive,90
12,103,Alexander,Hunold,590.423.4567,9000,IT,60
13,104,Bruce,Ernst,590.423.4568,6000,IT,60
14,105,David,Austin,590.423.4569,4800,IT,60
15,106,Valli,Pataballa,590.423.4560,4800,IT,60
16,107,Diana,Lorentz,590.423.5567,4200,IT,60
17,108,Nancy,Greenberg,515.124.4569,12008,Finance,100
18,109,Daniel,Faviet,515.124.4169,9000,Finance,100
19,110,John,Chen,515.124.4269,8200,Finance,100
20,111,Ismael,Sciarra,515.124.4369,7700,Finance,100
21,112,Jose Manuel,Urman,515.124.4469,7800,Finance,100
22,113,Luis,Popp,515.124.4567,6900,Finance,100
23,114,Den,Raphaely,515.127.4561,11000,Purchasing,30
24,115,Alexander,Khoo,515.127.4562,3100,Purchasing,30
25,116,Shelli,Baida,515.127.4563,2900,Purchasing,30
26,117,Sigal,Tobias,515.127.4564,2800,Purchasing,30
27,118,Guy,Himuro,515.127.4565,2600,Purchasing,30
28,119,Karen,Colmenares,515.127.4566,2500,Purchasing,30
29,120,Matthew,Weiss,650.123.1234,8000,Shipping,50
30,121,Adam,Fripp,650.123.2234,8200,Shipping,50
31,122,Payam,Kaufling,650.123.3234,7900,Shipping,50
32,123,Shanta,Vollman,650.123.4234,6500,Shipping,50
33,124,Kevin,Mourgos,650.123.5234,5800,Shipping,50
34,125,Julia,Nayer,650.124.1214,3200,Shipping,50
35,126,Irene,Mikkilineni,650.124.1224,2700,Shipping,50
36,127,James,Landry,650.124.1334,2400,Shipping,50
37,128,Steven,Markle,650.124.1434,2200,Shipping,50
38,129,Laura,Bissot,650.124.5234,3300,Shipping,50
39,130,Mozhe,Atkinson,650.124.6234,2800,Shipping,50
40,131,James,Marlow,650.124.7234,2500,Shipping,50
41,132,TJ,Olson,650.124.8234,2100,Shipping,50
42,133,Jason,Mallin,650.127.1934,3300,Shipping,50
43,134,Michael,Rogers,650.127.1834,2900,Shipping,50
44,135,Ki,Gee,650.127.1734,2400,Shipping,50
45,136,Hazel,Philtanker,650.127.1634,2200,Shipping,50
46,137,Renske,Ladwig,650.121.1234,3600,Shipping,50
47,138,Stephen,Stiles,650.121.2034,3200,Shipping,50
48,139,John,Seo,650.121.2019,2700,Shipping,50
49,140,Joshua,Patel,650.121.1834,2500,Shipping,50

In [16]:
result = pd.merge(
        employee_data, 
        department_data, 
        on="DEPARTMENT_ID", 
        how="inner"
    )[["EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "PHONE_NUMBER", "SALARY", "DEPARTMENT_NAME", "DEPARTMENT_ID"]]

result.columns = ["EMPLOYEE ID", "FIRST NAME", "LAST NAME", "PHONE NUMBER", "SALARY", "DEPARTMENT NAME", "DEPARTMENT ID"] # Rename the columns

result

,EMPLOYEE ID,FIRST NAME,LAST NAME,PHONE NUMBER,SALARY,DEPARTMENT NAME,DEPARTMENT ID
0,198,Donald,OConnell,650.507.9833,2600,Shipping,50
1,199,Douglas,Grant,650.507.9844,2600,Shipping,50
2,200,Jennifer,Whalen,515.123.4444,4400,Administration,10
3,201,Michael,Hartstein,515.123.5555,13000,Marketing,20
4,202,Pat,Fay,603.123.6666,6000,Marketing,20
5,203,Susan,Mavris,515.123.7777,6500,Human Resources,40
6,204,Hermann,Baer,515.123.8888,10000,Public Relations,70
7,205,Shelley,Higgins,515.123.8080,12008,Accounting,110
8,206,William,Gietz,515.123.8181,8300,Accounting,110
9,100,Steven,King,515.123.4567,24000,Executive,90
10,101,Neena,Kochhar,515.123.4568,17000,Executive,90
11,102,Lex,De Haan,515.123.4569,17000,Executive,90
12,103,Alexander,Hunold,590.423.4567,9000,IT,60
13,104,Bruce,Ernst,590.423.4568,6000,IT,60
14,105,David,Austin,590.423.4569,4800,IT,60
15,106,Valli,Pataballa,590.423.4560,4800,IT,60
16,107,Diana,Lorentz,590.423.5567,4200,IT,60
17,108,Nancy,Greenberg,515.124.4569,12008,Finance,100
18,109,Daniel,Faviet,515.124.4169,9000,Finance,100
19,110,John,Chen,515.124.4269,8200,Finance,100
20,111,Ismael,Sciarra,515.124.4369,7700,Finance,100
21,112,Jose Manuel,Urman,515.124.4469,7800,Finance,100
22,113,Luis,Popp,515.124.4567,6900,Finance,100
23,114,Den,Raphaely,515.127.4561,11000,Purchasing,30
24,115,Alexander,Khoo,515.127.4562,3100,Purchasing,30
25,116,Shelli,Baida,515.127.4563,2900,Purchasing,30
26,117,Sigal,Tobias,515.127.4564,2800,Purchasing,30
27,118,Guy,Himuro,515.127.4565,2600,Purchasing,30
28,119,Karen,Colmenares,515.127.4566,2500,Purchasing,30
29,120,Matthew,Weiss,650.123.1234,8000,Shipping,50
30,121,Adam,Fripp,650.123.2234,8200,Shipping,50
31,122,Payam,Kaufling,650.123.3234,7900,Shipping,50
32,123,Shanta,Vollman,650.123.4234,6500,Shipping,50
33,124,Kevin,Mourgos,650.123.5234,5800,Shipping,50
34,125,Julia,Nayer,650.124.1214,3200,Shipping,50
35,126,Irene,Mikkilineni,650.124.1224,2700,Shipping,50
36,127,James,Landry,650.124.1334,2400,Shipping,50
37,128,Steven,Markle,650.124.1434,2200,Shipping,50
38,129,Laura,Bissot,650.124.5234,3300,Shipping,50
39,130,Mozhe,Atkinson,650.124.6234,2800,Shipping,50
40,131,James,Marlow,650.124.7234,2500,Shipping,50
41,132,TJ,Olson,650.124.8234,2100,Shipping,50
42,133,Jason,Mallin,650.127.1934,3300,Shipping,50
43,134,Michael,Rogers,650.127.1834,2900,Shipping,50
44,135,Ki,Gee,650.127.1734,2400,Shipping,50
45,136,Hazel,Philtanker,650.127.1634,2200,Shipping,50
46,137,Renske,Ladwig,650.121.1234,3600,Shipping,50
47,138,Stephen,Stiles,650.121.2034,3200,Shipping,50
48,139,John,Seo,650.121.2019,2700,Shipping,50
49,140,Joshua,Patel,650.121.1834,2500,Shipping,50

### 2.2 Left Join

 - Returns all records from the left DataFrame (Employee).

In [20]:
result = pd.merge(
        employee_data, 
        department_data, 
        on="DEPARTMENT_ID", 
        how="left"
    )[["EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "PHONE_NUMBER", "SALARY", "DEPARTMENT_NAME", "DEPARTMENT_ID"]]

result

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,SALARY,DEPARTMENT_NAME,DEPARTMENT_ID
0,198,Donald,OConnell,650.507.9833,2600,Shipping,50
1,199,Douglas,Grant,650.507.9844,2600,Shipping,50
2,200,Jennifer,Whalen,515.123.4444,4400,Administration,10
3,201,Michael,Hartstein,515.123.5555,13000,Marketing,20
4,202,Pat,Fay,603.123.6666,6000,Marketing,20
5,203,Susan,Mavris,515.123.7777,6500,Human Resources,40
6,204,Hermann,Baer,515.123.8888,10000,Public Relations,70
7,205,Shelley,Higgins,515.123.8080,12008,Accounting,110
8,206,William,Gietz,515.123.8181,8300,Accounting,110
9,100,Steven,King,515.123.4567,24000,Executive,90
10,101,Neena,Kochhar,515.123.4568,17000,Executive,90
11,102,Lex,De Haan,515.123.4569,17000,Executive,90
12,103,Alexander,Hunold,590.423.4567,9000,IT,60
13,104,Bruce,Ernst,590.423.4568,6000,IT,60
14,105,David,Austin,590.423.4569,4800,IT,60
15,106,Valli,Pataballa,590.423.4560,4800,IT,60
16,107,Diana,Lorentz,590.423.5567,4200,IT,60
17,108,Nancy,Greenberg,515.124.4569,12008,Finance,100
18,109,Daniel,Faviet,515.124.4169,9000,Finance,100
19,110,John,Chen,515.124.4269,8200,Finance,100
20,111,Ismael,Sciarra,515.124.4369,7700,Finance,100
21,112,Jose Manuel,Urman,515.124.4469,7800,Finance,100
22,113,Luis,Popp,515.124.4567,6900,Finance,100
23,114,Den,Raphaely,515.127.4561,11000,Purchasing,30
24,115,Alexander,Khoo,515.127.4562,3100,Purchasing,30
25,116,Shelli,Baida,515.127.4563,2900,Purchasing,30
26,117,Sigal,Tobias,515.127.4564,2800,Purchasing,30
27,118,Guy,Himuro,515.127.4565,2600,Purchasing,30
28,119,Karen,Colmenares,515.127.4566,2500,Purchasing,30
29,120,Matthew,Weiss,650.123.1234,8000,Shipping,50
30,121,Adam,Fripp,650.123.2234,8200,Shipping,50
31,122,Payam,Kaufling,650.123.3234,7900,Shipping,50
32,123,Shanta,Vollman,650.123.4234,6500,Shipping,50
33,124,Kevin,Mourgos,650.123.5234,5800,Shipping,50
34,125,Julia,Nayer,650.124.1214,3200,Shipping,50
35,126,Irene,Mikkilineni,650.124.1224,2700,Shipping,50
36,127,James,Landry,650.124.1334,2400,Shipping,50
37,128,Steven,Markle,650.124.1434,2200,Shipping,50
38,129,Laura,Bissot,650.124.5234,3300,Shipping,50
39,130,Mozhe,Atkinson,650.124.6234,2800,Shipping,50
40,131,James,Marlow,650.124.7234,2500,Shipping,50
41,132,TJ,Olson,650.124.8234,2100,Shipping,50
42,133,Jason,Mallin,650.127.1934,3300,Shipping,50
43,134,Michael,Rogers,650.127.1834,2900,Shipping,50
44,135,Ki,Gee,650.127.1734,2400,Shipping,50
45,136,Hazel,Philtanker,650.127.1634,2200,Shipping,50
46,137,Renske,Ladwig,650.121.1234,3600,Shipping,50
47,138,Stephen,Stiles,650.121.2034,3200,Shipping,50
48,139,John,Seo,650.121.2019,2700,Shipping,50
49,140,Joshua,Patel,650.121.1834,2500,Shipping,50

### 2.3 Right Join

 - Returns all records from the right DataFrame (Department) with matching employee record details. If not matching then it should shows 'NaN'

In [21]:
result = pd.merge(
        employee_data, 
        department_data, 
        on="DEPARTMENT_ID", 
        how="right"
    )[["EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "PHONE_NUMBER", "SALARY", "DEPARTMENT_NAME", "DEPARTMENT_ID"]]

result

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,SALARY,DEPARTMENT_NAME,DEPARTMENT_ID
0,200.0,Jennifer,Whalen,515.123.4444,4400.0,Administration,10
1,201.0,Michael,Hartstein,515.123.5555,13000.0,Marketing,20
2,202.0,Pat,Fay,603.123.6666,6000.0,Marketing,20
3,114.0,Den,Raphaely,515.127.4561,11000.0,Purchasing,30
4,115.0,Alexander,Khoo,515.127.4562,3100.0,Purchasing,30
...,...,...,...,...,...,...,...
62,NaN,NaN,NaN,NaN,NaN,IT Helpdesk,230
63,NaN,NaN,NaN,NaN,NaN,Government Sales,240
64,NaN,NaN,NaN,NaN,NaN,Retail Sales,250
65,NaN,NaN,NaN,NaN,NaN,Recruiting,260
66,NaN,NaN,NaN,NaN,NaN,Payroll,270

### 2.4 Outer Join

- Returns all records from both DataFrames

In [22]:
result = pd.merge(
        employee_data, 
        department_data, 
        on="DEPARTMENT_ID", 
        how="outer"
    )[["EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "PHONE_NUMBER", "SALARY", "DEPARTMENT_NAME", "DEPARTMENT_ID"]]

result

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,SALARY,DEPARTMENT_NAME,DEPARTMENT_ID
0,200.0,Jennifer,Whalen,515.123.4444,4400.0,Administration,10
1,201.0,Michael,Hartstein,515.123.5555,13000.0,Marketing,20
2,202.0,Pat,Fay,603.123.6666,6000.0,Marketing,20
3,114.0,Den,Raphaely,515.127.4561,11000.0,Purchasing,30
4,115.0,Alexander,Khoo,515.127.4562,3100.0,Purchasing,30
...,...,...,...,...,...,...,...
62,NaN,NaN,NaN,NaN,NaN,IT Helpdesk,230
63,NaN,NaN,NaN,NaN,NaN,Government Sales,240
64,NaN,NaN,NaN,NaN,NaN,Retail Sales,250
65,NaN,NaN,NaN,NaN,NaN,Recruiting,260
66,NaN,NaN,NaN,NaN,NaN,Payroll,270

## Task #3 - List Comprehension 2 examples

 - List comprehension is a short way to create a new list from an existing iterable

#### 3.1 Get even numbers

In [23]:
numbers = [1, 2, 3, 4, 5, 6]

even_numbers = [x for x in numbers if x % 2 == 0]

print(even_numbers)

[2, 4, 6]

#### 3.2 Multiple if conditions

In [26]:
numbers = [2, 4, 6, 8, 10, 12, 15]

result = [x for x in numbers if x % 2 == 0 if x > 5]

print(result)

[6, 8, 10, 12]

#### 3.3 Multiple for loops

In [27]:
numbers = [1, 2, 3]
letters = ['A', 'B']

result = [(x, y) for x in numbers for y in letters]

print(result)

[(1, 'A'), (1, 'B'), (2, 'A'), (2, 'B'), (3, 'A'), (3, 'B')]

#### 3.4 Multiple for + if

In [28]:
result = [
    (x, y)
    for x in range(1, 4)
    for y in range(1, 4)
    if x != y
]

print(result)

[(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]

## Task #4 Lambda Function 2 examples with Map, Filter, Reduce

- A lambda function is an anonymous function written in a single line.

### 4.1 Map

 - Transforms each element in a collection and returns a new collection containing the transformed values.

#### 4.1.1 Multiply every number by 2

In [35]:
numbers = [2,4,7,19,45,50, 34,67,98]

result = list(map(lambda x: x * 2, numbers))

result

[4, 8, 14, 38, 90, 100, 68, 134, 196]

#### 4.1.2 Convert names to Uppercase

In [34]:
names = ["Prakash", "Raju", "Kamala", "Sharmila", "Divyadharshana", "Gokulakannan"]

result = list(map(lambda x: x.upper(), names))

result

['PRAKASH', 'RAJU', 'KAMALA', 'SHARMILA', 'DIVYADHARSHANA', 'GOKULAKANNAN']

### 4.2 Filter

 - Selects elements from a collection that satisfy a given condition.

#### 4.2.1 Get only even numbers

In [37]:
numbers = [2,4,7,19,45,50, 34,67,98]

result = list(filter(lambda x : x % 2 == 0, numbers))

result

[2, 4, 50, 34, 98]

#### 4.2.2 Get the above 30 numbers

In [38]:
numbers = [2,4,7,19,45,50, 34,67,98]

result = list(filter(lambda x : x  > 30, numbers))

result

[45, 50, 34, 67, 98]

### 4.3 Reduce

 - Keeps only elements where the condition is True.
 - Combines all elements of a collection into a single value using an accumulator.

In [39]:
from functools import reduce

#### 4.3.1 Calculate the sum of all numbers

In [40]:
numbers = [30000, 45600, 5432.56, 34547]

result = reduce(lambda x, y: x + y, numbers)

result

115579.56

#### 4.3.2 Find the largest number

In [41]:
numbers = [30000, 45600, 5432.56, 34547]

result = reduce(lambda x, y:x if x > y else y, numbers)

result

45600