## Top 8 Powerful functions in Python for Deeper Data Analysis

1. Group By
2. Pivot Table
3. Aggregate
4. Cross Tab
5. Concat
6. Merge
7. Apply
8. Lamda
9. Del (Keyword)

## 1. Groupby function

In [1]:
import pandas as pd

In [2]:
insurance_data = pd.read_csv("Insurance.csv")
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

### 1.1 Perform Initial Analysis

In [5]:
insurance_data.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [6]:
insurance_data.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [7]:
insurance_data.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

### 1.2 Pull up the average Insurance charges based on region

In [8]:
insurance_data["region"].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [12]:
insurance_data.groupby(by="region")["charges"].mean().sort_values().round(2)

region
southwest    12346.94
northwest    12417.58
northeast    13406.38
southeast    14735.41
Name: charges, dtype: float64

### 1.2 Pull up the average Insurance charges based on region and sex

In [5]:
insurance_data.groupby(by=["region", "sex"])["charges"].max().sort_values(ascending=False).round(2)

region     sex
southeast  female    63770.43
           male      62592.87
northwest  male      60021.40
northeast  female    58571.07
northwest  female    55135.40
southwest  male      52590.83
           female    48824.45
northeast  male      48549.18
Name: charges, dtype: float64

## 2. Pivot Table

In [7]:
pd.pivot_table(data=insurance_data, values="charges", index="region", columns=["sex","children"]).round()

sex         female                                                  male  \
children         0        1        2        3        4        5        0
region
northeast   9790.0  17125.0  14523.0  13730.0  14542.0      NaN  13390.0
northwest  12584.0  11119.0  13128.0  13431.0  11024.0   8966.0   9813.0
southeast  14862.0   9870.0  11766.0  19723.0  18267.0   9924.0  13792.0
southwest  10150.0  10842.0  16230.0   8439.0  10946.0  10024.0  13727.0

sex
children         1        2        3        4        5
region
northeast  15474.0  12318.0  14935.0  14442.0   6979.0
northwest   9515.0  13763.0  22971.0  11508.0      NaN
southeast  17425.0  18648.0  17102.0   8727.0  10307.0
southwest   9971.0  18876.0  12072.0  17924.0   6865.0

## 3. Aggregate

### 3.1 Find out the average insurance charges based on Region

In [11]:
insurance_data.groupby(by=["region"])["charges"].mean().sort_values(ascending=False).round(2)

region
southeast    14735.41
northeast    13406.38
northwest    12417.58
southwest    12346.94
Name: charges, dtype: float64

In [15]:
insurance_data.groupby(by=["region","sex"])["charges"].agg(func=["mean", "min","max","sum"]).round()

                     mean     min      max        sum
region    sex
northeast female  12953.0  2196.0  58571.0  2085466.0
          male    13854.0  1695.0  48549.0  2258203.0
northwest female  12480.0  2117.0  55135.0  2046699.0
          male    12354.0  1621.0  60021.0  1989013.0
southeast female  13500.0  1608.0  63770.0  2362442.0
          male    15880.0  1122.0  62593.0  3001248.0
southwest female  11274.0  1728.0  48824.0  1826455.0
          male    13413.0  1242.0  52591.0  2186300.0

## 4. Cross Tab

In [17]:
insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

#### 4.1 Find out the numbers of smokers and non-smokers based on region

In [19]:
pd.crosstab(index=insurance_data["region"], columns=insurance_data["smoker"], margins=True)

smoker       no  yes   All
region
northeast   257   67   324
northwest   267   58   325
southeast   273   91   364
southwest   267   58   325
All        1064  274  1338

## 5. Concat

In [315]:
sales_data_2017 = pd.read_csv("Sales_Transactions_2017.csv")
sales_data_2018 = pd.read_csv("Sales_Transactions_2018.csv")
sales_data_2019 = pd.read_csv("Sales_Transactions_2019.csv")
sales_data_edited = pd.read_csv("Sales_Transactions_Edit.csv")

In [137]:
sales_data_2017

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2019,Sal:687,BALAJI PLASTICS,DONA-VAI-9100,1,"1,730.00","1,730.00",NaN,"3,460.00"
1,1/4/2019,Sal:687,BALAJI PLASTICS,SMART BOUL(48),1,"1,730.00","1,730.00",NaN,NaN
2,1/4/2019,Sal:688,BALAJI PLASTICS,Vishnu Ice,110,18.5,"2,035.00",NaN,"2,035.00"
3,,,28/3,,0,0,,,
4,1/4/2019,Sal:689,BALAJI PLASTICS,100LEAF -SP,3,585,"1,755.00",NaN,"1,755.00"
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [138]:
sales_data_2018

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2018,Sal:146,TP13,SILVER POUCH 9*12,50,85,"4,250.00",NaN,"66,724.00"
1,1/4/2018,Sal:146,TP13,RUBBER,5,290,"1,450.00",NaN,NaN
2,1/4/2018,Sal:146,TP13,DURGA 10*12 Blue,"1,600.00",5.5,"8,800.00",NaN,NaN
3,1/4/2018,Sal:146,TP13,DURGA 13*16 BLUE,400,11,"4,400.00",NaN,NaN
4,1/4/2018,Sal:146,TP13,10*12 SARAS-NAT,600,8.1,"4,860.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
44735,31/03/2019,Sal:9610,HAMPI FOODS,SPOON SOOFY,200,40,"8,000.00",NaN,NaN
44736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44738,NaN,Total,NaN,NaN,"666,056.00","1,067,808.80","10,796,991.30","29,999.00","10,787,647.30"
44739,NaN,Total,NaN,NaN,"7,097,803.00","10,024,197.00","117,897,671.80","720,204.00","117,427,983.80"

In [139]:
sales_data_2019

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
47285,31/03/2018,Sal:10042,Vkp,10*10 SHEET,25,137,"3,425.00",NaN,"3,425.00"
47286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47288,NaN,Total,NaN,NaN,"607,734.60","669,300.49","9,953,816.13","106,607.00","9,868,583.13"
47289,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71"

In [140]:
sales_data_edited

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0
...,...,...,...,...,...,...
95557,12/9/2019,4265,TP13,SPOON MED M.W,20,11.0
95558,12/9/2019,4266,K.SRIHARI,SMART BOUL(48),1,1830.0
95559,12/9/2019,4267,SMS,SMARTBOUL GLA(4000),1,1520.0
95560,12/9/2019,4268,ANILFANCY,RR WINEGLASS,100,20.0
95561,12/9/2019,4268,ANILFANCY,RR WATER GLASS,100,20.0

In [316]:
sales_data_edited.dtypes

Date        object
Voucher      int64
Party       object
Product     object
Qty          int64
Rate       float64
dtype: object

In [367]:
sales_all_data = pd.concat(objs=[sales_data_2017,sales_data_2018, sales_data_2019])
sales_all_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2019,Sal:687,BALAJI PLASTICS,DONA-VAI-9100,1,"1,730.00","1,730.00",NaN,"3,460.00"
1,1/4/2019,Sal:687,BALAJI PLASTICS,SMART BOUL(48),1,"1,730.00","1,730.00",NaN,NaN
2,1/4/2019,Sal:688,BALAJI PLASTICS,Vishnu Ice,110,18.5,"2,035.00",NaN,"2,035.00"
3,,,28/3,,0,0,,,
4,1/4/2019,Sal:689,BALAJI PLASTICS,100LEAF -SP,3,585,"1,755.00",NaN,"1,755.00"
...,...,...,...,...,...,...,...,...,...
47285,31/03/2018,Sal:10042,Vkp,10*10 SHEET,25,137,"3,425.00",NaN,"3,425.00"
47286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47288,NaN,Total,NaN,NaN,"607,734.60","669,300.49","9,953,816.13","106,607.00","9,868,583.13"
47289,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71"

In [318]:
sales_all_data.dtypes

Date              object
Voucher           object
Party             object
Product           object
Qty               object
Rate              object
Gross             object
Disc              object
Voucher Amount    object
dtype: object

In [319]:
sales_all_data.isna().sum()

Date               12591
Voucher            12557
Party                 40
Product            12591
Qty                12557
Rate               12558
Gross              12558
Disc              105609
Voucher Amount     83646
dtype: int64

In [320]:
sales_all_data.shape

(111206, 9)

In [368]:
sales_all_data.drop_duplicates(inplace=True)
sales_all_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2019,Sal:687,BALAJI PLASTICS,DONA-VAI-9100,1,"1,730.00","1,730.00",NaN,"3,460.00"
1,1/4/2019,Sal:687,BALAJI PLASTICS,SMART BOUL(48),1,"1,730.00","1,730.00",NaN,NaN
2,1/4/2019,Sal:688,BALAJI PLASTICS,Vishnu Ice,110,18.5,"2,035.00",NaN,"2,035.00"
3,,,28/3,,0,0,,,
4,1/4/2019,Sal:689,BALAJI PLASTICS,100LEAF -SP,3,585,"1,755.00",NaN,"1,755.00"
...,...,...,...,...,...,...,...,...,...
47281,31/03/2018,Sal:10041,HARITHA BEACH RESOR,APPLE WATER,10,25,250,NaN,NaN
47283,31/03/2018,Sal:10041,HARITHA BEACH RESOR,BLACK DOG-350ML,10,26,260,NaN,NaN
47285,31/03/2018,Sal:10042,Vkp,10*10 SHEET,25,137,"3,425.00",NaN,"3,425.00"
47288,NaN,Total,NaN,NaN,"607,734.60","669,300.49","9,953,816.13","106,607.00","9,868,583.13"
47289,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71"

In [369]:
sales_all_data.isna().sum()

Date                204
Voucher             170
Party                35
Product             204
Qty                 170
Rate                171
Gross               171
Disc              92951
Voucher Amount    70984
dtype: int64

In [370]:
valid_sales_all_data = sales_all_data[sales_all_data["Date"].notna() & 
    sales_all_data["Voucher"].notna()  & 
    #sales_all_data["Party"].notna() &
    #sales_all_data["Product"].notna()  & 
    sales_all_data["Qty"].notna()  & 
    sales_all_data["Rate"].notna()]

valid_sales_all_data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2019,Sal:687,BALAJI PLASTICS,DONA-VAI-9100,1,"1,730.00","1,730.00",NaN,"3,460.00"
1,1/4/2019,Sal:687,BALAJI PLASTICS,SMART BOUL(48),1,"1,730.00","1,730.00",NaN,NaN
2,1/4/2019,Sal:688,BALAJI PLASTICS,Vishnu Ice,110,18.5,"2,035.00",NaN,"2,035.00"
3,,,28/3,,0,0,,,
4,1/4/2019,Sal:689,BALAJI PLASTICS,100LEAF -SP,3,585,"1,755.00",NaN,"1,755.00"
...,...,...,...,...,...,...,...,...,...
47277,31/03/2018,Sal:10041,HARITHA BEACH RESOR,PAPER TEA 150ML,10,40,400,NaN,NaN
47279,31/03/2018,Sal:10041,HARITHA BEACH RESOR,PRINT 13*16,2,120,240,NaN,NaN
47281,31/03/2018,Sal:10041,HARITHA BEACH RESOR,APPLE WATER,10,25,250,NaN,NaN
47283,31/03/2018,Sal:10041,HARITHA BEACH RESOR,BLACK DOG-350ML,10,26,260,NaN,NaN
47285,31/03/2018,Sal:10042,Vkp,10*10 SHEET,25,137,"3,425.00",NaN,"3,425.00"

In [371]:
valid_sales_all_data.isna().sum()

Date                  0
Voucher               0
Party                 0
Product               0
Qty                   0
Rate                  0
Gross                 0
Disc              92780
Voucher Amount    70813
dtype: int64

In [372]:
# valid_sales_all_data = valid_sales_all_data.drop(columns=["Gross", "Disc", "Voucher Amount"])
valid_sales_all_data = valid_sales_all_data[["Date","Voucher","Party","Product","Qty","Rate"]]
valid_sales_all_data

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2019,Sal:687,BALAJI PLASTICS,DONA-VAI-9100,1,"1,730.00"
1,1/4/2019,Sal:687,BALAJI PLASTICS,SMART BOUL(48),1,"1,730.00"
2,1/4/2019,Sal:688,BALAJI PLASTICS,Vishnu Ice,110,18.5
3,,,28/3,,0,0
4,1/4/2019,Sal:689,BALAJI PLASTICS,100LEAF -SP,3,585
...,...,...,...,...,...,...
47277,31/03/2018,Sal:10041,HARITHA BEACH RESOR,PAPER TEA 150ML,10,40
47279,31/03/2018,Sal:10041,HARITHA BEACH RESOR,PRINT 13*16,2,120
47281,31/03/2018,Sal:10041,HARITHA BEACH RESOR,APPLE WATER,10,25
47283,31/03/2018,Sal:10041,HARITHA BEACH RESOR,BLACK DOG-350ML,10,26
47285,31/03/2018,Sal:10042,Vkp,10*10 SHEET,25,137

In [373]:
valid_sales_all_data.isna().sum()

valid_sales_all_data.shape

(96419, 6)

In [327]:
valid_sales_all_data.dtypes

Date       object
Voucher    object
Party      object
Product    object
Qty        object
Rate       object
dtype: object

In [374]:
valid_sales_all_data = valid_sales_all_data.copy()

valid_sales_all_data["Voucher"] = (
    valid_sales_all_data["Voucher"]
    .astype(str)
    .str.replace("Sal:", "", regex=False)
)

valid_sales_all_data

             Date Voucher                Party          Product  Qty      Rate
0        1/4/2019     687      BALAJI PLASTICS    DONA-VAI-9100    1  1,730.00
1        1/4/2019     687      BALAJI PLASTICS   SMART BOUL(48)    1  1,730.00
2        1/4/2019     688      BALAJI PLASTICS       Vishnu Ice  110      18.5
3                                         28/3                     0         0
4        1/4/2019     689      BALAJI PLASTICS      100LEAF -SP    3       585
...           ...     ...                  ...              ...  ...       ...
47277  31/03/2018   10041  HARITHA BEACH RESOR  PAPER TEA 150ML   10        40
47279  31/03/2018   10041  HARITHA BEACH RESOR      PRINT 13*16    2       120
47281  31/03/2018   10041  HARITHA BEACH RESOR      APPLE WATER   10        25
47283  31/03/2018   10041  HARITHA BEACH RESOR  BLACK DOG-350ML   10        26
47285  31/03/2018   10042                  Vkp      10*10 SHEET   25       137

[96419 rows x 6 columns]

In [375]:
valid_sales_all_data.isna().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       0
dtype: int64

In [376]:
valid_sales_all_data.dtypes

Date       object
Voucher    object
Party      object
Product    object
Qty        object
Rate       object
dtype: object

In [377]:
valid_sales_all_data = valid_sales_all_data.replace(r'^\s*$', pd.NA, regex=True)
valid_sales_all_data = valid_sales_all_data.dropna().reset_index(drop=True)

valid_sales_all_data

             Date Voucher                Party          Product  Qty      Rate
0        1/4/2019     687      BALAJI PLASTICS    DONA-VAI-9100    1  1,730.00
1        1/4/2019     687      BALAJI PLASTICS   SMART BOUL(48)    1  1,730.00
2        1/4/2019     688      BALAJI PLASTICS       Vishnu Ice  110      18.5
3        1/4/2019     689      BALAJI PLASTICS      100LEAF -SP    3       585
4        2/4/2019       1                  Tvr    BAHUBALI WINE  110        25
...           ...     ...                  ...              ...  ...       ...
95281  31/03/2018   10041  HARITHA BEACH RESOR  PAPER TEA 150ML   10        40
95282  31/03/2018   10041  HARITHA BEACH RESOR      PRINT 13*16    2       120
95283  31/03/2018   10041  HARITHA BEACH RESOR      APPLE WATER   10        25
95284  31/03/2018   10041  HARITHA BEACH RESOR  BLACK DOG-350ML   10        26
95285  31/03/2018   10042                  Vkp      10*10 SHEET   25       137

[95286 rows x 6 columns]

In [378]:
valid_sales_all_data["Voucher"] = valid_sales_all_data["Voucher"].str.replace("Sal:","").astype(int)

In [379]:
valid_sales_all_data.dtypes

Date       object
Voucher     int64
Party      object
Product    object
Qty        object
Rate       object
dtype: object

In [380]:
valid_sales_all_data["Qty"] = pd.to_numeric(
    valid_sales_all_data["Qty"].astype(str).str.replace(",", "", regex=False),
    errors="coerce"
).astype(int)

In [381]:
valid_sales_all_data.dtypes

Date       object
Voucher     int64
Party      object
Product    object
Qty         int64
Rate       object
dtype: object

In [382]:
valid_sales_all_data

,Date,Voucher,Party,Product,Qty,Rate
0,1/4/2019,687,BALAJI PLASTICS,DONA-VAI-9100,1,"1,730.00"
1,1/4/2019,687,BALAJI PLASTICS,SMART BOUL(48),1,"1,730.00"
2,1/4/2019,688,BALAJI PLASTICS,Vishnu Ice,110,18.5
3,1/4/2019,689,BALAJI PLASTICS,100LEAF -SP,3,585
4,2/4/2019,1,Tvr,BAHUBALI WINE,110,25
...,...,...,...,...,...,...
95281,31/03/2018,10041,HARITHA BEACH RESOR,PAPER TEA 150ML,10,40
95282,31/03/2018,10041,HARITHA BEACH RESOR,PRINT 13*16,2,120
95283,31/03/2018,10041,HARITHA BEACH RESOR,APPLE WATER,10,25
95284,31/03/2018,10041,HARITHA BEACH RESOR,BLACK DOG-350ML,10,26
95285,31/03/2018,10042,Vkp,10*10 SHEET,25,137

In [383]:
valid_sales_all_data["Rate"] = pd.to_numeric(
    valid_sales_all_data["Rate"].astype(str).str.replace(",", "", regex=False),
    errors="coerce"
).astype(float)

In [384]:
valid_sales_all_data.dtypes

Date        object
Voucher      int64
Party       object
Product     object
Qty          int64
Rate       float64
dtype: object

In [385]:
valid_sales_all_data

             Date  Voucher                Party          Product  Qty    Rate
0        1/4/2019      687      BALAJI PLASTICS    DONA-VAI-9100    1  1730.0
1        1/4/2019      687      BALAJI PLASTICS   SMART BOUL(48)    1  1730.0
2        1/4/2019      688      BALAJI PLASTICS       Vishnu Ice  110    18.5
3        1/4/2019      689      BALAJI PLASTICS      100LEAF -SP    3   585.0
4        2/4/2019        1                  Tvr    BAHUBALI WINE  110    25.0
...           ...      ...                  ...              ...  ...     ...
95281  31/03/2018    10041  HARITHA BEACH RESOR  PAPER TEA 150ML   10    40.0
95282  31/03/2018    10041  HARITHA BEACH RESOR      PRINT 13*16    2   120.0
95283  31/03/2018    10041  HARITHA BEACH RESOR      APPLE WATER   10    25.0
95284  31/03/2018    10041  HARITHA BEACH RESOR  BLACK DOG-350ML   10    26.0
95285  31/03/2018    10042                  Vkp      10*10 SHEET   25   137.0

[95286 rows x 6 columns]

In [386]:
valid_sales_all_data.isna().sum()

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       0
dtype: int64

In [402]:
valid_sales_all_data["Date"] = pd.to_datetime(
    valid_sales_all_data["Date"],
    format="%d/%m/%Y",
    errors="coerce"
)

In [403]:
valid_sales_all_data

            Date  Voucher                Party          Product  Qty    Rate
0     2019-04-01      687      BALAJI PLASTICS    DONA-VAI-9100    1  1730.0
1     2019-04-01      687      BALAJI PLASTICS   SMART BOUL(48)    1  1730.0
2     2019-04-01      688      BALAJI PLASTICS       Vishnu Ice  110    18.5
3     2019-04-01      689      BALAJI PLASTICS      100LEAF -SP    3   585.0
4     2019-04-02        1                  Tvr    BAHUBALI WINE  110    25.0
...          ...      ...                  ...              ...  ...     ...
95281 2018-03-31    10041  HARITHA BEACH RESOR  PAPER TEA 150ML   10    40.0
95282 2018-03-31    10041  HARITHA BEACH RESOR      PRINT 13*16    2   120.0
95283 2018-03-31    10041  HARITHA BEACH RESOR      APPLE WATER   10    25.0
95284 2018-03-31    10041  HARITHA BEACH RESOR  BLACK DOG-350ML   10    26.0
95285 2018-03-31    10042                  Vkp      10*10 SHEET   25   137.0

[95286 rows x 6 columns]

In [404]:
print(valid_sales_all_data.dtypes)

Date       datetime64[ns]
Voucher             int64
Party              object
Product            object
Qty                 int64
Rate              float64
dtype: object

## 6. Merge

**Common merge types**

**left** — keep all rows from the first DataFrame

**right** — keep all rows from the second DataFrame

**inner** — keep only matching rows

**outer** — keep all rows from both

In [412]:
merge_data = pd.merge(
    sales_data_2017, 
    sales_data_2018,
    how="inner",
left_on="Date",
right_on="Date")

merge_data

,Date,Voucher_x,Party_x,Product_x,Qty_x,Rate_x,Gross_x,Disc_x,Voucher Amount_x,Voucher_y,Party_y,Product_y,Qty_y,Rate_y,Gross_y,Disc_y,Voucher Amount_y
0,,,28/3,,0,0,,,,,d.veerabadram,,,,,,
1,,,28/3,,0,0,,,,,DUMMY ENTRY,,,,,,
2,,,28/3,,0,0,,,,,credit bill,,,,,,
3,,,28/3,,0,0,,,,,credit bill,,,,,,
4,,,28/3,,0,0,,,,,svr brandi,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10274181,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40",NaN,RKINN,NaN,NaN,NaN,NaN,NaN,NaN
10274182,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10274183,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10274184,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40",Total,NaN,NaN,"666,056.00","1,067,808.80","10,796,991.30","29,999.00","10,787,647.30"
10274185,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40",Total,NaN,NaN,"7,097,803.00","10,024,197.00","117,897,671.80","720,204.00","117,427,983.80"

#### 7. Apply

In [3]:
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

##### 7.1 Create a new column in the same dataframe with the name "Eligibility Criteria" where the age > 20, say Eligible else Not Eligible

In [4]:
def get_eligible_by_age(x):
    if x > 20:
        return "Eligible"
    else:
        return "Not Eligible"

In [5]:
insurance_data["Eligibility Criteria"] = insurance_data["age"].apply(get_eligible_by_age)

insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligibility Criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible

### 8. Lambda function

* Anoynous / nameless function

In [6]:
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligibility Criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible

In [7]:
insurance_data["EC"] = insurance_data["age"].apply(lambda x: "Eligible" if x > 20 else "Not Eligible")

insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligibility Criteria,EC
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible,Not Eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible,Not Eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible,Eligible
...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible,Not Eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible,Not Eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible,Eligible

#### 8.1 Explore List Comprehension for 3 examples

#### 8.2 Explore lambda - Map, Filter and Query

## Del Keyword

* Delete only one column

In [8]:
del insurance_data["EC"]

insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligibility Criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible