## 1. Write a program to take a name and age from the user and print a greeting message

In [4]:
user_name = input("Enter the Name: ")
user_age = input("Enter the Age: ")

print(f"Hello {user_name}, Welcome to or Data Science and Machine Learning Course. Please confirm your age is: {user_age}.")

Enter the Name:  PRakash Raju
Enter the Age:  42

Hello PRakash Raju, Welcome to or Data Science and Machine Learning Course. Please confirm your age is: 42.

## 2. Create a list of numbers and print only event numbers using a for loop

In [6]:
even_nums = []
for i in range(1,100):
    if i%2 == 0:
       even_nums.append(i)

print(even_nums)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]

## 3. Write a program that handles division by zero using try-except

In [16]:
try:
    numerator = int(input("Enter Numerator: "))
    denaminator = int(input("Enter Denaminator: "))
    result = numerator/denaminator
    print(result)

except ZeroDivisionError:
    print("Please enter denaminator is greater than 0")

except ValueError:
    print("Please enter the numbers only")

finally:
    print("Program Ended !!!")

Enter Numerator:  46456
Enter Denaminator:  456

101.87719298245614
Program Ended !!!

## 4. Give a string, count how many vowels it has

In [25]:
user_input = input("Enter a string: ")

vowel_count = 0

for i in user_input.lower():
    if i in 'aeiou': 
        vowel_count += 1

print(f"Total number of vowels are: {vowel_count}")

Enter a string:  Prakash Raju

Total number of vowels are: 4

## 5. Reverse a list without using built-in functions

In [37]:
list_data = [2,3,5,7,8,9]
#list_data.reverse()
rev_data = []

tot_len = len(list_data) - 1

# for i in range(len(list_data)-1,-1,-1):
#     rev_data.append(list_data[i])

while tot_len >= 0:
    rev_data.append(list_data[tot_len])
    tot_len -= 1
    
print(rev_data)

[9, 8, 7, 5, 3, 2]

## 6. Create a dictionary with at least 5 key-value pairs and print them

In [63]:
import pandas as pd

dict_name = {"name": ["Prakash", "Sharmila", "Divyadharshana", "Gokulakannan", "Kamala", "Raju"],
            "age": [42, 39, 13, 11, 65, 72],
            "city": ["Salem", "Coimbatore", "Chennai", "Bangalore", "Mumbai", "Kolkatta"],
            "degree": ["MCA", "BE", "12th", "10th", "5th", "PUC"],
            "sex":["Male", "Female", "Female", "Male", "Female", "Male"]}

dict_name

pd.DataFrame(data=dict_name)

             name  age        city degree     sex
0         Prakash   42       Salem    MCA    Male
1        Sharmila   39  Coimbatore     BE  Female
2  Divyadharshana   13     Chennai   12th  Female
3    Gokulakannan   11   Bangalore   10th    Male
4          Kamala   65      Mumbai    5th  Female
5            Raju   72    Kolkatta    PUC    Male

## 7. Write a CSV file suing Pandas and print top 5 rows

In [52]:
emp_data=pd.read_csv("employees.csv")
emp_data.head(5)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,HIRE_DATE,SALARY,MANAGER_ID,ROLE
0,198,Donald,OConnell,650.507.9833,21-Jun-07,2600.0,124.0,DevOps
1,199,Douglas,Grant,650.507.9844,13-Jan-08,2600.0,124.0,Developer
2,200,Jennifer,Whalen,515.123.4444,17-Sep-03,4400.0,101.0,Tester
3,201,Michael,Hartstein,515.123.5555,17-Feb-04,NaN,100.0,Lead Developer
4,202,Pat,Fay,603.123.6666,17-Aug-05,6000.0,201.0,AI Developer

## 8. Create a DataFrame from a Python Dictionary

In [53]:
pd.DataFrame(data=dict_name)

             name  age        city degree     sex
0         Prakash   42       Salem    MCA    Male
1        Sharmila   39  Coimbatore     BE  Female
2  Divyadharshana   13     Chennai   12th  Female
3    Gokulakannan   11   Bangalore   10th    Male
4          Kamala   65      Mumbai    5th  Female
5            Raju   72    Kolkatta    PUC    Male

## 9. Replace all misiing values in a DataFrame with the coulmn's mean

In [60]:
emp_data["SALARY"].mean()

np.float64(6215.565217391304)

In [61]:
emp_data["SALARY"].fillna(value=emp_data["SALARY"].mean(), inplace=True)
emp_data

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,HIRE_DATE,SALARY,MANAGER_ID,ROLE
0,198,Donald,OConnell,650.507.9833,21-Jun-07,2600.000000,124.0,DevOps
1,199,Douglas,Grant,650.507.9844,13-Jan-08,2600.000000,124.0,Developer
2,200,Jennifer,Whalen,515.123.4444,17-Sep-03,4400.000000,101.0,Tester
3,201,Michael,Hartstein,515.123.5555,17-Feb-04,6215.565217,100.0,Lead Developer
4,202,Pat,Fay,603.123.6666,17-Aug-05,6000.000000,201.0,AI Developer
5,203,NaN,NaN,515.123.7777,07-Jun-02,6500.000000,101.0,Developer
6,204,Hermann,Baer,515.123.8888,07-Jun-02,10000.000000,101.0,AI Architect
7,205,Shelley,Higgins,515.123.8080,07-Jun-02,12008.000000,101.0,Tester
8,206,William,Gietz,515.123.8181,07-Jun-02,8300.000000,205.0,DevOps
9,100,Steven,King,515.123.4567,17-Jun-03,24000.000000,NaN,Lead Developer
10,101,Neena,Kochhar,515.123.4568,21-Sep-05,17000.000000,100.0,AI Developer
11,102,Lex,De Haan,515.123.4569,13-Jan-01,17000.000000,100.0,Lead Developer
12,103,Alexander,Hunold,590.423.4567,03-Jan-06,9000.000000,102.0,Tester
13,104,Bruce,Ernst,590.423.4568,21-May-07,6000.000000,103.0,Developer
14,105,David,Austin,590.423.4569,25-Jun-05,6215.565217,103.0,AI Architect
15,106,Valli,Pataballa,590.423.4560,05-Feb-06,4800.000000,103.0,AI Developer
16,107,NaN,NaN,590.423.5567,07-Feb-07,4200.000000,103.0,Developer
17,108,Nancy,Greenberg,515.124.4569,17-Aug-02,12008.000000,101.0,Developer
18,109,Daniel,Faviet,515.124.4169,16-Aug-02,9000.000000,108.0,AI Architect
19,110,John,Chen,515.124.4269,28-Sep-05,8200.000000,108.0,Developer
20,111,Ismael,Sciarra,515.124.4369,30-Sep-05,7700.000000,108.0,Developer
21,112,Jose Manuel,Urman,515.124.4469,07-Mar-06,7800.000000,108.0,DevOps
22,113,Luis,Popp,515.124.4567,07-Dec-07,6900.000000,108.0,AI Architect
23,114,Den,Raphaely,515.127.4561,07-Dec-02,11000.000000,100.0,Lead Developer
24,115,Alexander,Khoo,515.127.4562,18-May-03,3100.000000,114.0,Tester
25,116,NaN,NaN,515.127.4563,24-Dec-05,2900.000000,114.0,Lead Developer
26,117,Sigal,Tobias,515.127.4564,24-Jul-05,2800.000000,114.0,Developer
27,118,Guy,Himuro,515.127.4565,15-Nov-06,2600.000000,114.0,AI Developer
28,119,Karen,Colmenares,515.127.4566,10-Aug-07,6215.565217,114.0,AI Developer
29,120,Matthew,Weiss,650.123.1234,18-Jul-04,8000.000000,100.0,DevOps
30,121,Adam,Fripp,650.123.2234,10-Apr-05,8200.000000,100.0,DevOps
31,122,Payam,Kaufling,650.123.3234,01-May-03,7900.000000,100.0,Developer
32,123,NaN,NaN,650.123.4234,10-Oct-05,6500.000000,100.0,AI Developer
33,124,Kevin,Mourgos,650.123.5234,16-Nov-07,5800.000000,100.0,AI Developer
34,125,Julia,Nayer,650.124.1214,16-Jul-05,3200.000000,120.0,DevOps
35,126,Irene,Mikkilineni,650.124.1224,28-Sep-06,2700.000000,120.0,Tester
36,127,James,Landry,650.124.1334,14-Jan-07,2400.000000,120.0,Developer
37,128,Steven,Markle,650.124.1434,08-Mar-08,2200.000000,NaN,AI Developer
38,129,Laura,Bissot,650.124.5234,20-Aug-05,3300.000000,121.0,Developer
39,130,Mozhe,Atkinson,650.124.6234,30-Oct-05,2800.000000,121.0,Lead Developer
40,131,NaN,NaN,650.124.7234,16-Feb-05,2500.000000,121.0,AI Developer
41,132,TJ,Olson,650.124.8234,10-Apr-07,2100.000000,121.0,DevOps
42,133,Jason,Mallin,650.127.1934,14-Jun-04,3300.000000,122.0,Developer
43,134,Michael,Rogers,650.127.1834,26-Aug-06,6215.565217,122.0,Developer
44,135,Ki,Gee,650.127.1734,12-Dec-07,2400.000000,122.0,AI Architect
45,136,Hazel,Philtanker,650.127.1634,06-Feb-08,2200.000000,122.0,Tester
46,137,Renske,Ladwig,650.121.1234,14-Jul-03,3600.000000,123.0,Developer
47,138,NaN,NaN,650.121.2034,26-Oct-05,3200.000000,123.0,DevOps
48,139,John,Seo,650.121.2019,12-Feb-06,2700.000000,123.0,AI Architect
49,140,Joshua,Patel,650.121.1834,06-Apr-06,2500.000000,123.0,Developer

## 10. Filter rows in a DataFrame where the "SALARY" column is greater than 10000

In [69]:
emp_data["SALARY"] > 10000

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9      True
10     True
11     True
12    False
13    False
14    False
15    False
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23     True
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
Name: SALARY, dtype: bool

In [70]:
emp_data[emp_data["SALARY"] > 3000]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,HIRE_DATE,SALARY,MANAGER_ID,ROLE
2,200,Jennifer,Whalen,515.123.4444,17-Sep-03,4400.000000,101.0,Tester
3,201,Michael,Hartstein,515.123.5555,17-Feb-04,6215.565217,100.0,Lead Developer
4,202,Pat,Fay,603.123.6666,17-Aug-05,6000.000000,201.0,AI Developer
5,203,NaN,NaN,515.123.7777,07-Jun-02,6500.000000,101.0,Developer
6,204,Hermann,Baer,515.123.8888,07-Jun-02,10000.000000,101.0,AI Architect
7,205,Shelley,Higgins,515.123.8080,07-Jun-02,12008.000000,101.0,Tester
8,206,William,Gietz,515.123.8181,07-Jun-02,8300.000000,205.0,DevOps
9,100,Steven,King,515.123.4567,17-Jun-03,24000.000000,NaN,Lead Developer
10,101,Neena,Kochhar,515.123.4568,21-Sep-05,17000.000000,100.0,AI Developer
11,102,Lex,De Haan,515.123.4569,13-Jan-01,17000.000000,100.0,Lead Developer
12,103,Alexander,Hunold,590.423.4567,03-Jan-06,9000.000000,102.0,Tester
13,104,Bruce,Ernst,590.423.4568,21-May-07,6000.000000,103.0,Developer
14,105,David,Austin,590.423.4569,25-Jun-05,6215.565217,103.0,AI Architect
15,106,Valli,Pataballa,590.423.4560,05-Feb-06,4800.000000,103.0,AI Developer
16,107,NaN,NaN,590.423.5567,07-Feb-07,4200.000000,103.0,Developer
17,108,Nancy,Greenberg,515.124.4569,17-Aug-02,12008.000000,101.0,Developer
18,109,Daniel,Faviet,515.124.4169,16-Aug-02,9000.000000,108.0,AI Architect
19,110,John,Chen,515.124.4269,28-Sep-05,8200.000000,108.0,Developer
20,111,Ismael,Sciarra,515.124.4369,30-Sep-05,7700.000000,108.0,Developer
21,112,Jose Manuel,Urman,515.124.4469,07-Mar-06,7800.000000,108.0,DevOps
22,113,Luis,Popp,515.124.4567,07-Dec-07,6900.000000,108.0,AI Architect
23,114,Den,Raphaely,515.127.4561,07-Dec-02,11000.000000,100.0,Lead Developer
24,115,Alexander,Khoo,515.127.4562,18-May-03,3100.000000,114.0,Tester
28,119,Karen,Colmenares,515.127.4566,10-Aug-07,6215.565217,114.0,AI Developer
29,120,Matthew,Weiss,650.123.1234,18-Jul-04,8000.000000,100.0,DevOps
30,121,Adam,Fripp,650.123.2234,10-Apr-05,8200.000000,100.0,DevOps
31,122,Payam,Kaufling,650.123.3234,01-May-03,7900.000000,100.0,Developer
32,123,NaN,NaN,650.123.4234,10-Oct-05,6500.000000,100.0,AI Developer
33,124,Kevin,Mourgos,650.123.5234,16-Nov-07,5800.000000,100.0,AI Developer
34,125,Julia,Nayer,650.124.1214,16-Jul-05,3200.000000,120.0,DevOps
38,129,Laura,Bissot,650.124.5234,20-Aug-05,3300.000000,121.0,Developer
42,133,Jason,Mallin,650.127.1934,14-Jun-04,3300.000000,122.0,Developer
43,134,Michael,Rogers,650.127.1834,26-Aug-06,6215.565217,122.0,Developer
46,137,Renske,Ladwig,650.121.1234,14-Jul-03,3600.000000,123.0,Developer
47,138,NaN,NaN,650.121.2034,26-Oct-05,3200.000000,123.0,DevOps