## DATA PREPROCESSING / DATA PREPARATION

1. Data Cleaning - Drop, Fillna with mean, median, model Imputation, changing dtypes
2. Data Transformation
   - If data is CONTINUES => Standard Scaler, MinMaxScaler, Robust Scaler
   - If data is DISTRETE => Label Encoder, One hot Encoder

### 1. Import Necessary Libraries

In [87]:
import pandas as pd

import warnings
warnings.filterwarnings(action="ignore")

### 2. Import Dataset

In [48]:
weather_data = pd.read_csv("environmental_data.csv")

weather_data

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5    NaN      NaN  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

### 3. Data Understanding

#### 3.1 Perfom Initial Analysis on the Data

In [49]:
weather_data.shape

(158, 10)

In [50]:
weather_data.isna().sum()

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

In [51]:
weather_data.dtypes

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C         object
Month          object
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

In [52]:
weather_data.describe(include="all")

,Unnamed: 0,Ozone,Solar.R,Wind,Temp C,Month,Day,Year,Temp,Weather
count,158.000000,120.000000,151.000000,158.000000,158,158,158.000000,158.0,158.000000,155
unique,NaN,NaN,NaN,NaN,41,6,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,81,9,NaN,NaN,NaN,S
freq,NaN,NaN,NaN,NaN,11,34,NaN,NaN,NaN,59
mean,79.500000,41.583333,185.403974,9.957595,NaN,NaN,16.006329,2010.0,77.727848,NaN
std,45.754781,32.620709,88.723103,3.511261,NaN,NaN,8.997166,0.0,9.377877,NaN
min,1.000000,1.000000,7.000000,1.700000,NaN,NaN,1.000000,2010.0,56.000000,NaN
25%,40.250000,18.000000,119.000000,7.400000,NaN,NaN,8.000000,2010.0,72.000000,NaN
50%,79.500000,30.500000,197.000000,9.700000,NaN,NaN,16.000000,2010.0,78.500000,NaN
75%,118.750000,61.500000,257.000000,11.875000,NaN,NaN,24.000000,2010.0,84.000000,NaN
max,158.000000,168.000000,334.000000,20.700000,NaN,NaN,31.000000,2010.0,97.000000,NaN

In [54]:
weather_data["Weather"].unique()

array(['S', 'C', 'PS', nan], dtype=object)

In [55]:
weather_data["Weather"].value_counts(dropna=False)

Weather
S      59
C      49
PS     47
NaN     3
Name: count, dtype: int64

### 4. Data Perparation

#### 4.1 Data Cleaning - drop, fillna with mean, median, mode Imputation, changing dtype

In [56]:
weather_data.head(10)

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S
5           6   28.0      NaN  14.9     66     5    6  2010    66       C
6           7   23.0    299.0   8.6     65     5    7  2010    65      PS
7           8   19.0     99.0  13.8     59     5    8  2010    59       C
8           9    8.0     19.0  20.1     61     5    9  2010    61      PS
9          10    NaN    194.0   8.6     69     5   10  2010    69       S

##### We removed unwanted columns - "Unnamed:0" and "Temp C"

In [57]:
weather_data.drop(labels=["Unnamed: 0", "Temp C"], axis=1, inplace=True)

weather_data.head(20)

    Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0    41.0    190.0   7.4     5    1  2010    67       S
1    36.0    118.0   8.0     5    2  2010    72       C
2    12.0    149.0  12.6     5    3  2010    74      PS
3    18.0    313.0  11.5     5    4  2010    62       S
4     NaN      NaN  14.3     5    5  2010    56       S
5    28.0      NaN  14.9     5    6  2010    66       C
6    23.0    299.0   8.6     5    7  2010    65      PS
7    19.0     99.0  13.8     5    8  2010    59       C
8     8.0     19.0  20.1     5    9  2010    61      PS
9     NaN    194.0   8.6     5   10  2010    69       S
10    7.0      NaN   6.9     5   11  2010    74       C
11   16.0    256.0   9.7     5   12  2010    69      PS
12   11.0    290.0   9.2     5   13  2010    66       S
13   14.0    274.0  10.9     5   14  2010    68       S
14   18.0     65.0  13.2     5   15  2010    58       C
15   14.0    334.0  11.5     5   16  2010    64       S
16   34.0    307.0  12.0     5   17  2010    66       S
17    6.0     78.0  18.4     5   18  2010    57       C
18   30.0    322.0  11.5     5   19  2010    68      PS
19   11.0     44.0   9.7     5   20  2010    62       S

In [58]:
weather_data.isna().sum()

Ozone      38
Solar.R     7
Wind        0
Month       0
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [59]:
weather_data.shape

(158, 8)

In [60]:
38/158

0.24050632911392406

##### I'm dropping the column "OZone", as 25% of the data is NaN

In [61]:
del weather_data["Ozone"]

In [62]:
weather_data.shape

(158, 7)

In [63]:
weather_data.isna().sum()

Solar.R    7
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [64]:
weather_data.head(15)

    Solar.R  Wind Month  Day  Year  Temp Weather
0     190.0   7.4     5    1  2010    67       S
1     118.0   8.0     5    2  2010    72       C
2     149.0  12.6     5    3  2010    74      PS
3     313.0  11.5     5    4  2010    62       S
4       NaN  14.3     5    5  2010    56       S
5       NaN  14.9     5    6  2010    66       C
6     299.0   8.6     5    7  2010    65      PS
7      99.0  13.8     5    8  2010    59       C
8      19.0  20.1     5    9  2010    61      PS
9     194.0   8.6     5   10  2010    69       S
10      NaN   6.9     5   11  2010    74       C
11    256.0   9.7     5   12  2010    69      PS
12    290.0   9.2     5   13  2010    66       S
13    274.0  10.9     5   14  2010    68       S
14     65.0  13.2     5   15  2010    58       C

In [65]:
7/158

0.04430379746835443

In [66]:
weather_data["Solar.R"].isna()

0      False
1      False
2      False
3      False
4       True
       ...
153    False
154    False
155    False
156    False
157    False
Name: Solar.R, Length: 158, dtype: bool

In [69]:
weather_data.groupby("Weather")["Solar.R"].mean().round()

Weather
C     192.0
PS    174.0
S     193.0
Name: Solar.R, dtype: float64

In [76]:
weather_data["Solar.R"] = weather_data.groupby("Weather")["Solar.R"].transform(lambda x:x.fillna(x.mean().round()))
weather_data

     Solar.R  Wind Month  Day  Year  Temp Weather
0      190.0   7.4     5    1  2010    67       S
1      118.0   8.0     5    2  2010    72       C
2      149.0  12.6     5    3  2010    74      PS
3      313.0  11.5     5    4  2010    62       S
4      193.0  14.3     5    5  2010    56       S
..       ...   ...   ...  ...   ...   ...     ...
153    190.0   7.4     5    1  2010    67       C
154    193.0   6.9     9   26  2010    70      PS
155    145.0  13.2     9   27  2010    77       S
156    191.0  14.3     9   28  2010    75       S
157    131.0   8.0     9   29  2010    76       C

[158 rows x 7 columns]

In [77]:
weather_data.isna().sum()

Solar.R    3
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [78]:
weather_data[weather_data["Solar.R"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
87      NaN  12.0     7   27  2010    86     NaN
93      NaN  13.8     8    2  2010    81     NaN
95      NaN   6.9     8    4  2010    86     NaN

In [79]:
weather_data.dropna(inplace=True)

In [80]:
weather_data.isna().sum()

Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [82]:
wheather_data.shape

(158, 9)

In [81]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [83]:
weather_data.Month.unique()

array(['5', 'May', '6', '7', '8', '9'], dtype=object)

In [84]:
weather_data.head(30)

    Solar.R  Wind Month  Day  Year  Temp Weather
0     190.0   7.4     5    1  2010    67       S
1     118.0   8.0     5    2  2010    72       C
2     149.0  12.6     5    3  2010    74      PS
3     313.0  11.5     5    4  2010    62       S
4     193.0  14.3     5    5  2010    56       S
5     192.0  14.9     5    6  2010    66       C
6     299.0   8.6     5    7  2010    65      PS
7      99.0  13.8     5    8  2010    59       C
8      19.0  20.1     5    9  2010    61      PS
9     194.0   8.6     5   10  2010    69       S
10    192.0   6.9     5   11  2010    74       C
11    256.0   9.7     5   12  2010    69      PS
12    290.0   9.2     5   13  2010    66       S
13    274.0  10.9     5   14  2010    68       S
14     65.0  13.2     5   15  2010    58       C
15    334.0  11.5     5   16  2010    64       S
16    307.0  12.0     5   17  2010    66       S
17     78.0  18.4     5   18  2010    57       C
18    322.0  11.5     5   19  2010    68      PS
19     44.0   9.7     5   20  2010    62       S
20      8.0   9.7     5   21  2010    59       S
21    320.0  16.6     5   22  2010    73       C
22     25.0   9.7     5   23  2010    61      PS
23     92.0  12.0   May   24  2010    61       C
24     66.0  16.6     5   25  2010    57      PS
25    266.0  14.9     5   26  2010    58       C
26    174.0   8.0     5   27  2010    57      PS
27     13.0  12.0     5   28  2010    67       S
28    252.0  14.9     5   29  2010    81       S
29    223.0   5.7     5   30  2010    79       C

In [85]:
weather_data.replace(to_replace="May", value=5, inplace=True)

weather_data

     Solar.R  Wind Month  Day  Year  Temp Weather
0      190.0   7.4     5    1  2010    67       S
1      118.0   8.0     5    2  2010    72       C
2      149.0  12.6     5    3  2010    74      PS
3      313.0  11.5     5    4  2010    62       S
4      193.0  14.3     5    5  2010    56       S
..       ...   ...   ...  ...   ...   ...     ...
153    190.0   7.4     5    1  2010    67       C
154    193.0   6.9     9   26  2010    70      PS
155    145.0  13.2     9   27  2010    77       S
156    191.0  14.3     9   28  2010    75       S
157    131.0   8.0     9   29  2010    76       C

[155 rows x 7 columns]

In [86]:
weather_data.Month.unique()

array(['5', 5, '6', '7', '8', '9'], dtype=object)

In [88]:
weather_data["Month"] = weather_data["Month"].astype("int")

In [89]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

##### 2. Data Transfromation

In [90]:
weather_data.head(10)

   Solar.R  Wind  Month  Day  Year  Temp Weather
0    190.0   7.4      5    1  2010    67       S
1    118.0   8.0      5    2  2010    72       C
2    149.0  12.6      5    3  2010    74      PS
3    313.0  11.5      5    4  2010    62       S
4    193.0  14.3      5    5  2010    56       S
5    192.0  14.9      5    6  2010    66       C
6    299.0   8.6      5    7  2010    65      PS
7     99.0  13.8      5    8  2010    59       C
8     19.0  20.1      5    9  2010    61      PS
9    194.0   8.6      5   10  2010    69       S

In [91]:
weather_data_copy_01 = weather_data.copy()

weather_data_copy_01

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

In [92]:
from sklearn.preprocessing import LabelEncoder

In [94]:
le_encoder = LabelEncoder()

weather_data_copy_01["Weather"] = le_encoder.fit_transform(weather_data_copy_01["Weather"])

weather_data_copy_01

     Solar.R  Wind  Month  Day  Year  Temp  Weather
0      190.0   7.4      5    1  2010    67        2
1      118.0   8.0      5    2  2010    72        0
2      149.0  12.6      5    3  2010    74        1
3      313.0  11.5      5    4  2010    62        2
4      193.0  14.3      5    5  2010    56        2
..       ...   ...    ...  ...   ...   ...      ...
153    190.0   7.4      5    1  2010    67        0
154    193.0   6.9      9   26  2010    70        1
155    145.0  13.2      9   27  2010    77        2
156    191.0  14.3      9   28  2010    75        2
157    131.0   8.0      9   29  2010    76        0

[155 rows x 7 columns]

In [95]:
weather_data_copy_01.dtypes

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather      int64
dtype: object

## How do we convert and transform the column data

### 1. One Hot Encoder

This can be achieved by using any of the following 2 libraries:

1. Pandas - pd.getdummies() - it is used to creating the unique column values as new columns
2. sklearn - OneHotEncoder()

#### 1.1 Pandas - pd.getdummies()

In [107]:
weather_data_copy_02 = weather_data.copy()

weather_data_copy_02

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

In [108]:
weather_data_copy_02["Weather"].unique()

array(['S', 'C', 'PS'], dtype=object)

In [109]:
# pd.getdummies() - it is used to creating the unique column values as new columns
weather_data_copy_02 = pd.get_dummies(data=weather_data_copy_02, columns=["Weather"], dtype="int")

weather_data_copy_02

     Solar.R  Wind  Month  Day  Year  Temp  Weather_C  Weather_PS  Weather_S
0      190.0   7.4      5    1  2010    67          0           0          1
1      118.0   8.0      5    2  2010    72          1           0          0
2      149.0  12.6      5    3  2010    74          0           1          0
3      313.0  11.5      5    4  2010    62          0           0          1
4      193.0  14.3      5    5  2010    56          0           0          1
..       ...   ...    ...  ...   ...   ...        ...         ...        ...
153    190.0   7.4      5    1  2010    67          1           0          0
154    193.0   6.9      9   26  2010    70          0           1          0
155    145.0  13.2      9   27  2010    77          0           0          1
156    191.0  14.3      9   28  2010    75          0           0          1
157    131.0   8.0      9   29  2010    76          1           0          0

[155 rows x 9 columns]

In [110]:
weather_data_copy_02.dtypes

Solar.R       float64
Wind          float64
Month           int64
Day             int64
Year            int64
Temp            int64
Weather_C       int64
Weather_PS      int64
Weather_S       int64
dtype: object

In [130]:
weather_data_copy_03 = weather_data.copy()

weather_data_copy_03

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

### 2. sklearn - OneHotEncoder()

In [137]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# 1. Make a copy of your original DataFrame
weather_data_copy_03 = weather_data.copy()

# 2. Check the DataFrame
print(weather_data_copy_03.head())

# 3. Create OneHotEncoder
ohe = OneHotEncoder(sparse_output=False)

# 4. Encode the Weather column
weather_encoded = ohe.fit_transform(
    weather_data_copy_03[["Weather"]]
)

# 5. Display encoded values
print(weather_encoded)

# 6. Get the new column names
encoded_columns = ohe.get_feature_names_out(["Weather"])

print(encoded_columns)

# 7. Convert encoded data into a DataFrame
encoded_df = pd.DataFrame(
    weather_encoded,
    columns=encoded_columns,
    index=weather_data_copy_03.index
)

# 8. Add encoded columns to the original DataFrame
weather_data_copy_03 = pd.concat(
    [weather_data_copy_03, encoded_df],
    axis=1
)

# 9. Display the final DataFrame
print(weather_data_copy_03.head())

   Solar.R  Wind  Month  Day  Year  Temp Weather
0    190.0   7.4      5    1  2010    67       S
1    118.0   8.0      5    2  2010    72       C
2    149.0  12.6      5    3  2010    74      PS
3    313.0  11.5      5    4  2010    62       S
4    193.0  14.3      5    5  2010    56       S
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]]
['Weather_C' 'Weather_PS' 'Weather_S']
   Solar.R  Wind  Month  Day  Year  Temp Weather  Weather_C  Weather_PS  \
0    190.0   7.4      5    1  2010    67       S        0.0         0.0
1    118.0   8.0      5    2  2010    72       C        1.0         0.0
2    149.0  12.6      5    3  2010    74      PS        0.0         1.0
3    313.0  11.5      5    4  2010    62       S        0.0         0.0
4    193.0  14.3      5    5  2010    56       S        0.0         0.0

   Weather_S
0        1.0
1        0.0
2        0.0
3        1.0
4        1.0

-------------------------------

## How to choose between Label Encoder and One Hot Encoder?

### Input feature:
Based on whether it is **Parametric or a Non Parametric Model**, we will choosing between LE or OHE.
* For **Parametric Models** - better to go with **OHE.**
* For **Non-Parametric Models** - always go with **Label Encoding.**

### Output feature:
Always the output feature, it must be **Label Encoder.**

## THE END !!!