## Data Analystics Steps
* Business Understanding
* Data Collection
* Data Understanding (Analysis step - Chapter 1)
* Data Preparation (Data Cleaning - Chapter 2)
*

## Chapter 1: Getting & Knowing your Data

In [3]:
import pandas as pd

In [8]:
order_details = pd.read_csv("Orders.csv")
order_details

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity,Sales,Order ID,Price
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Illinois,Addison,60101,5/28/2012,5/30/2012,1.320000,2,5.90,88525,₹ 5.76
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,Washington,Anacortes,98221,07-07-2010,07-08-2010,4.560000,4,13.01,88522,₹ 11.36
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,Washington,Anacortes,98221,7/27/2011,7/28/2011,-47.640000,7,49.92,88523,₹ 46.76
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,Washington,Anacortes,98221,7/27/2011,7/28/2011,-30.510000,7,41.64,88523,₹ 39.76
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,Washington,Anacortes,98221,7/27/2011,7/27/2011,998.202300,8,1446.67,88523,"₹ 1,647.92"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,West Virginia,Charleston,25314,5/14/2013,5/15/2013,137.860000,13,447.87,87532,₹ 466.57
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,West Virginia,Charleston,25314,5/14/2013,5/14/2013,-39.070000,3,13.23,87532,₹ 10.02
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,West Virginia,Charleston,25314,09-12-2013,9/14/2013,-1225.029097,4,2215.93,87533,"₹ 2,203.92"
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,Wyoming,Cheyenne,82001,02-08-2010,02-11-2010,349.485000,5,506.50,87530,₹ 529.90
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,Wyoming,Cheyenne,82001,09-12-2013,9/14/2013,78.062400,23,172.48,87533,₹ 178.94

## 1.1 Perform Initial Analysis
1. Check if null or empty values
2. List down the data types
3. Describe the data
----
* Funtion - ()
* Attribute - Properties

In [25]:
order_details.shape # returns rows and column count

(9426, 24)

### Terminology Alert
* Row - Observations / Record
* Column - Features / Parameters

In [26]:
order_details.isnull().sum() # Chain of functions/commands

Row ID                   0
Order Priority           0
Discount                 0
Unit Price               0
Shipping Cost            0
Customer ID              0
Customer Name            0
Ship Mode                0
Customer Segment         0
Product Category         0
Product Sub-Category     0
Product Container        0
Product Name             0
Product Base Margin     72
Region                   0
State or Province        0
City                     0
Postal Code              0
Order Date               0
Ship Date                0
Profit                   0
Quantity                 0
Sales                    0
Order ID                 0
dtype: int64

In [27]:
order_details.dtypes

Row ID                    int64
Order Priority           object
Discount                float64
Unit Price              float64
Shipping Cost           float64
Customer ID               int64
Customer Name            object
Ship Mode                object
Customer Segment         object
Product Category         object
Product Sub-Category     object
Product Container        object
Product Name             object
Product Base Margin     float64
Region                   object
State or Province        object
City                     object
Postal Code               int64
Order Date               object
Ship Date                object
Profit                  float64
Quantity                  int64
Sales                   float64
Order ID                  int64
dtype: object

In [28]:
order_details.describe(include='all')

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity,Sales,Order ID
count,9426.000000,9426,9426.000000,9426.000000,9426.000000,9426.000000,9426,9426,9426,9426,...,9426,9426,9426,9426.000000,9426,9426,9426.000000,9426.000000,9426.000000,9426.000000
unique,NaN,6,NaN,NaN,NaN,NaN,2703,3,4,3,...,4,49,1424,NaN,1419,1450,NaN,NaN,NaN,NaN
top,NaN,High,NaN,NaN,NaN,NaN,Louis Parrish,Regular Air,Corporate,Office Supplies,...,Central,California,New York City,NaN,7/21/2013,05-09-2013,NaN,NaN,NaN,NaN
freq,NaN,1970,NaN,NaN,NaN,NaN,27,7036,3375,5181,...,2899,1021,202,NaN,24,21,NaN,NaN,NaN,NaN
mean,20241.015277,NaN,0.049628,88.303686,12.795142,1738.422236,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,52446.327286,NaN,NaN,139.236410,13.798430,949.706272,82318.489073
std,6101.890965,NaN,0.031798,281.540982,17.181203,979.167197,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,29374.597802,NaN,NaN,998.486483,15.107688,2598.019818,19149.448857
min,2.000000,NaN,0.000000,0.990000,0.490000,2.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1001.000000,NaN,NaN,-16476.838000,1.000000,1.320000,6.000000
25%,19330.250000,NaN,0.020000,6.480000,3.192500,898.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,29406.000000,NaN,NaN,-74.017375,5.000000,61.282500,86737.250000
50%,21686.500000,NaN,0.050000,20.990000,6.050000,1750.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,52302.000000,NaN,NaN,2.567600,10.000000,203.455000,88344.500000
75%,24042.750000,NaN,0.080000,85.990000,13.990000,2578.750000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,78516.000000,NaN,NaN,140.243850,17.000000,776.402500,89987.750000
max,26399.000000,NaN,0.250000,6783.020000,164.730000,3403.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,99362.000000,NaN,NaN,16332.414000,170.000000,100119.160000,91591.000000

## 1.2 Find out the Items sold in the data

In [29]:
order_details.nunique() # Find uniquie values for each parameters/columns

Row ID                  9426
Order Priority             6
Discount                  16
Unit Price               751
Shipping Cost            652
Customer ID             2703
Customer Name           2703
Ship Mode                  3
Customer Segment           4
Product Category           3
Product Sub-Category      17
Product Container          7
Product Name            1263
Product Base Margin       51
Region                     4
State or Province         49
City                    1424
Postal Code             1697
Order Date              1419
Ship Date               1450
Profit                  8960
Quantity                 112
Sales                   8674
Order ID                6455
dtype: int64

In [30]:
print(order_details["Product Name"].unique()) # Find unique values for specific column

['Avery 49' 'SANFORD Liquid Accent™ Tank-Style Highlighters' 'Xerox 1968'
 ... 'DAX Wood Document Frame' 'R289LX' 'Alliance Rubber Bands']

## 1.3 Read the list of Top 5 Selling Items
* Groupby Product Name
* Sum of quantity for each items
* Descending the list
* Read the top 5 records

In [40]:
order_details.groupby(by="Product Name")["Quantity"].sum().sort_values(ascending=False).head(5)

Product Name
Avery 510                                                                        428
Executive Impressions 12" Wall Clock                                             409
US Robotics 56K V.92 Internal PCI Faxmodem                                       398
Verbatim DVD-RAM, 5.2GB, Rewritable, Type 1, DS                                  393
Office Star - Contemporary Task Swivel chair with 2-way adjustable arms, Plum    391
Name: Quantity, dtype: int64

## 1.4 Read the list of Least 5 Selling Items
* Groupby Product Name
* Sum of quantity for each items
* Ascending the list
* Read the top 5 records

In [41]:
order_details.groupby(by="Product Name")["Quantity"].sum().sort_values(ascending=True).head(5)

Product Name
Hewlett Packard 610 Color Digital Copier / Printer         1
APC 7 Outlet Network SurgeArrest Surge Protector           1
Eldon® Executive Woodline II Desk Accessories, Mahogany    2
Strathmore #10 Envelopes, Ultimate White                   2
14-7/8 x 11 Blue Bar Computer Printout Paper               2
Name: Quantity, dtype: int64

## Chapter 2 - Data Cleaning
* We should consider numberic data like Int, Float

In [5]:
order_details

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,5/28/2012,5/30/2012,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,07-07-2010,07-08-2010,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,7/27/2011,7/28/2011,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,7/27/2011,7/28/2011,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,7/27/2011,7/27/2011,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,5/14/2013,5/15/2013,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,5/14/2013,5/14/2013,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,09-12-2013,9/14/2013,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,02-08-2010,02-11-2010,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,09-12-2013,9/14/2013,78.062400,23,172.48,87533

In [9]:
order_details.dtypes

Row ID                    int64
Order Priority           object
Discount                float64
Unit Price              float64
Shipping Cost           float64
Customer ID               int64
Customer Name            object
Ship Mode                object
Customer Segment         object
Product Category         object
Product Sub-Category     object
Product Container        object
Product Name             object
Product Base Margin     float64
Region                   object
State or Province        object
City                     object
Postal Code               int64
Order Date               object
Ship Date                object
Profit                  float64
Quantity                  int64
Sales                   float64
Order ID                  int64
Price                    object
dtype: object

In [18]:
order_details["Price"].str.replace("₹", "").float()

AttributeError: 'Series' object has no attribute 'float'

In [25]:
order_details["Price"] = order_details["Price"].str.replace("₹", "").str.replace(",", "").astype(float)

In [27]:
order_details.dtypes

Row ID                    int64
Order Priority           object
Discount                float64
Unit Price              float64
Shipping Cost           float64
Customer ID               int64
Customer Name            object
Ship Mode                object
Customer Segment         object
Product Category         object
Product Sub-Category     object
Product Container        object
Product Name             object
Product Base Margin     float64
Region                   object
State or Province        object
City                     object
Postal Code               int64
Order Date               object
Ship Date                object
Profit                  float64
Quantity                  int64
Sales                   float64
Order ID                  int64
Price                   float64
dtype: object

In [28]:
order_details.describe()

,Row ID,Discount,Unit Price,Shipping Cost,Customer ID,Product Base Margin,Postal Code,Profit,Quantity,Sales,Order ID,Price
count,9426.000000,9426.000000,9426.000000,9426.000000,9426.000000,9354.000000,9426.000000,9426.000000,9426.000000,9426.000000,9426.000000,9426.000000
mean,20241.015277,0.049628,88.303686,12.795142,1738.422236,0.512189,52446.327286,139.236410,13.798430,949.706272,82318.489073,987.025262
std,6101.890965,0.031798,281.540982,17.181203,979.167197,0.135229,29374.597802,998.486483,15.107688,2598.019818,19149.448857,2680.873706
min,2.000000,0.000000,0.990000,0.490000,2.000000,0.350000,1001.000000,-16476.838000,1.000000,1.320000,6.000000,1.140000
25%,19330.250000,0.020000,6.480000,3.192500,898.000000,0.380000,29406.000000,-74.017375,5.000000,61.282500,86737.250000,59.880000
50%,21686.500000,0.050000,20.990000,6.050000,1750.000000,0.520000,52302.000000,2.567600,10.000000,203.455000,88344.500000,204.900000
75%,24042.750000,0.080000,85.990000,13.990000,2578.750000,0.590000,78516.000000,140.243850,17.000000,776.402500,89987.750000,822.105000
max,26399.000000,0.250000,6783.020000,164.730000,3403.000000,0.850000,99362.000000,16332.414000,170.000000,100119.160000,91591.000000,102193.680000

## Tasks
1. Find out the Top 5 Selling Items individual Revenue it made
2. Total Revenue of the Top 5 Items Sold

In [30]:
order_details.groupby(by="Product Name")["Quantity"].sum().sort_values(ascending=False).head(5)

Product Name
Avery 510                                                                        428
Executive Impressions 12" Wall Clock                                             409
US Robotics 56K V.92 Internal PCI Faxmodem                                       398
Verbatim DVD-RAM, 5.2GB, Rewritable, Type 1, DS                                  393
Office Star - Contemporary Task Swivel chair with 2-way adjustable arms, Plum    391
Name: Quantity, dtype: int64

In [31]:
order_details.groupby(by="Product Name")["Price"].sum().sort_values(ascending=False).head(5)

Product Name
Global Troy™ Executive Leather Low-Back Tilter                   195382.20
Riverside Palais Royal Lawyers Bookcase, Royale Cherry Finish    192934.62
Bretford CR8500 Series Meeting Room Furniture                    111478.20
Hewlett-Packard cp1700 [D, PS] Series Color Inkjet Printers      107209.72
Canon PC1080F Personal Copier                                    106198.23
Name: Price, dtype: float64

## Chapter 3 - Pandas Data Structure
* 1 Dimesional Data - Call it as Series
* 2 Dimesional Data - DataFrame

In [36]:
pd.Series(data=[11,23,56.7, '$23.6']) # It allows only 1D

0       11
1       23
2     56.7
3    $23.6
dtype: object

In [37]:
pd.DataFrame(data=[11,23,56.7, '$23.6'])

       0
0     11
1     23
2   56.7
3  $23.6

In [38]:
pd.DataFrame({
            "Name":["Prakash Raju", "Sharmila P", "Divaydharshana S P", "Gokulakannan S P"],
            "English": [60, 90, 95, 80],
              "Maths": [89, 95, 100, 92]
        })

                 Name  English  Maths
0        Prakash Raju       60     89
1          Sharmila P       90     95
2  Divaydharshana S P       95    100
3    Gokulakannan S P       80     92

### Tasks
1. Create a meaningful Series
2. Create a meaningful Dataset using Pandas with Dict 5 Observation across 6 Features

In [40]:
tuple_data=(34,67,23,68,89,23,78,56,85,95,35,78)
tuple_data

(34, 67, 23, 68, 89, 23, 78, 56, 85, 95, 35, 78)

In [42]:
pd.Series(tuple_data)

0     34
1     67
2     23
3     68
4     89
5     23
6     78
7     56
8     85
9     95
10    35
11    78
dtype: int64

In [41]:
dic_data={
            "EmployeeId": ["EMP001", "CON002", "EMP005", "EMP008", "CON005", "EMP006"],
            "EmployeeName": ["Prakash R", "Sharmila P", "Divyadharshana S P", "Gokulakannan S P", "Kamala R", "Raju M"],
            "Salary": [35000, 42000, 56000, 85000, 55000, 75000],
            "Department": ["Developer", "Tester", "DevOps Engineer", "Lead Developer", "AI Developer", "AI Architect"],
            "Sex": ["Male", "Female", "Female", "Male", "Female", "Male"]
        }

In [43]:
pd.DataFrame(dic_data)

  EmployeeId        EmployeeName  Salary       Department     Sex
0     EMP001           Prakash R   35000        Developer    Male
1     CON002          Sharmila P   42000           Tester  Female
2     EMP005  Divyadharshana S P   56000  DevOps Engineer  Female
3     EMP008    Gokulakannan S P   85000   Lead Developer    Male
4     CON005            Kamala R   55000     AI Developer  Female
5     EMP006              Raju M   75000     AI Architect    Male

## Chapter 4 - Filtering, Selection and Sorting

In [46]:
euro_2012_data = pd.read_csv("Euro 2012 stats TEAM.csv")
euro_2012_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [47]:
euro_2012_data.columns

Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork', 'Penalty goals', 'Penalties not scored', 'Headed goals',
       'Passes', 'Passes completed', 'Passing Accuracy', 'Touches', 'Crosses',
       'Dribbles', 'Corners Taken', 'Tackles', 'Clearances', 'Interceptions',
       'Clearances off line', 'Clean Sheets', 'Blocks', 'Goals conceded',
       'Saves made', 'Saves-to-shots ratio', 'Fouls Won', 'Fouls Conceded',
       'Offsides', 'Yellow Cards', 'Red Cards', 'Subs on', 'Subs off',
       'Players Used'],
      dtype='object')

In [49]:
euro_2012_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,Passes,Passes completed,Passing Accuracy,Touches,Crosses,Dribbles,Corners Taken,Tackles,Clearances,Interceptions,Clearances off line,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,2,1076,828,76.9%,1706,60,42,14,49,83,56,NaN,0,10,3,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,0,1565,1223,78.1%,2358,46,68,21,62,98,37,2.0,1,10,6,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,3,1298,1082,83.3%,1873,43,32,16,40,61,59,0.0,1,10,5,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,3,1488,1200,80.6%,2440,58,60,16,86,106,72,1.0,2,29,3,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,0,2066,1803,87.2%,2909,55,76,28,71,76,58,0.0,1,7,5,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,2774,2427,87.4%,3761,101,60,35,91,73,69,0.0,1,11,6,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,0,1187,911,76.7%,2016,52,53,10,65,123,87,0.0,1,23,7,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,2,3016,2531,83.9%,4363,75,75,30,98,137,136,1.0,2,18,7,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,0,1556,1381,88.7%,2163,50,49,22,34,41,41,0.0,0,9,5,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,1,1059,852,80.4%,1724,55,39,14,67,87,62,0.0,0,8,3,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,2,1891,1461,77.2%,2958,91,64,41,78,92,86,0.0,2,11,4,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,1,851,606,71.2%,1433,43,18,8,45,78,43,1.0,0,23,9,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,1,1602,1345,83.9%,2278,40,40,21,65,74,58,0.0,0,8,3,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,2,4317,3820,88.4%,5585,69,106,44,122,102,79,0.0,5,8,1,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,1,1192,965,80.9%,1806,44,29,7,56,54,45,0.0,1,12,5,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,2,1276,1043,81.7%,1894,33,26,18,65,97,29,0.0,0,4,4,13,76.5%,48,31,4,5,0,9,9,18

In [50]:
pd.set_option('display.max_columns', None) # Shows all columns

In [57]:
filtered_euro_data = euro_2012_data[["Team", "Goals", "Yellow Cards", "Red Cards"]] 
# Selections - "Team", "Goals", "Yellow Cards", "Red Cards"
filtered_euro_data

                   Team  Goals  Yellow Cards  Red Cards
0               Croatia      4             9          0
1        Czech Republic      4             7          0
2               Denmark      4             4          0
3               England      5             5          0
4                France      3             6          0
5               Germany     10             4          0
6                Greece      5             9          1
7                 Italy      6            16          0
8           Netherlands      2             5          0
9                Poland      2             7          1
10             Portugal      6            12          0
11  Republic of Ireland      1             6          1
12               Russia      5             6          0
13                Spain     12            11          0
14               Sweden      5             7          0
15              Ukraine      2             5          0

In [68]:
filtered_euro_data1=filtered_euro_data.filter(items=["Team", "Goals", "Yellow Cards", "Red Cards"])
filtered_euro_data1

                   Team  Goals  Yellow Cards  Red Cards
0               Croatia      4             9          0
1        Czech Republic      4             7          0
2               Denmark      4             4          0
3               England      5             5          0
4                France      3             6          0
5               Germany     10             4          0
6                Greece      5             9          1
7                 Italy      6            16          0
8           Netherlands      2             5          0
9                Poland      2             7          1
10             Portugal      6            12          0
11  Republic of Ireland      1             6          1
12               Russia      5             6          0
13                Spain     12            11          0
14               Sweden      5             7          0
15              Ukraine      2             5          0

In [60]:
filtered_euro_data.sort_values(by="Yellow Cards",ascending=False).head(5)

        Team  Goals  Yellow Cards  Red Cards
7      Italy      6            16          0
10  Portugal      6            12          0
13     Spain     12            11          0
0    Croatia      4             9          0
6     Greece      5             9          1

In [61]:
filtered_euro_data["Red Cards"] == 1

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9      True
10    False
11     True
12    False
13    False
14    False
15    False
Name: Red Cards, dtype: bool

In [62]:
filtered_euro_data[filtered_euro_data["Red Cards"] == 1]

                   Team  Goals  Yellow Cards  Red Cards
6                Greece      5             9          1
9                Poland      2             7          1
11  Republic of Ireland      1             6          1

In [66]:
filtered_euro_data[filtered_euro_data["Yellow Cards"] >= 8]

        Team  Goals  Yellow Cards  Red Cards
0    Croatia      4             9          0
6     Greece      5             9          1
7      Italy      6            16          0
10  Portugal      6            12          0
13     Spain     12            11          0

## Chapter 5 - Handling Missing Data

In [4]:
emplyees = pd.read_csv("employees.csv")
emplyees

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,HIRE_DATE,SALARY,MANAGER_ID,ROLE
0,198,Donald,OConnell,650.507.9833,21-Jun-07,2600.0,124.0,DevOps
1,199,Douglas,Grant,650.507.9844,13-Jan-08,2600.0,124.0,Developer
2,200,Jennifer,Whalen,515.123.4444,17-Sep-03,4400.0,101.0,Tester
3,201,Michael,Hartstein,515.123.5555,17-Feb-04,NaN,100.0,Lead Developer
4,202,Pat,Fay,603.123.6666,17-Aug-05,6000.0,201.0,AI Developer
5,203,NaN,NaN,515.123.7777,07-Jun-02,6500.0,101.0,Developer
6,204,Hermann,Baer,515.123.8888,07-Jun-02,10000.0,101.0,AI Architect
7,205,Shelley,Higgins,515.123.8080,07-Jun-02,12008.0,101.0,Tester
8,206,William,Gietz,515.123.8181,07-Jun-02,8300.0,205.0,DevOps
9,100,Steven,King,515.123.4567,17-Jun-03,24000.0,NaN,Lead Developer
10,101,Neena,Kochhar,515.123.4568,21-Sep-05,17000.0,100.0,AI Developer
11,102,Lex,De Haan,515.123.4569,13-Jan-01,17000.0,100.0,Lead Developer
12,103,Alexander,Hunold,590.423.4567,03-Jan-06,9000.0,102.0,Tester
13,104,Bruce,Ernst,590.423.4568,21-May-07,6000.0,103.0,Developer
14,105,David,Austin,590.423.4569,25-Jun-05,NaN,103.0,AI Architect
15,106,Valli,Pataballa,590.423.4560,05-Feb-06,4800.0,103.0,AI Developer
16,107,NaN,NaN,590.423.5567,07-Feb-07,4200.0,103.0,Developer
17,108,Nancy,Greenberg,515.124.4569,17-Aug-02,12008.0,101.0,Developer
18,109,Daniel,Faviet,515.124.4169,16-Aug-02,9000.0,108.0,AI Architect
19,110,John,Chen,515.124.4269,28-Sep-05,8200.0,108.0,Developer
20,111,Ismael,Sciarra,515.124.4369,30-Sep-05,7700.0,108.0,Developer
21,112,Jose Manuel,Urman,515.124.4469,07-Mar-06,7800.0,108.0,DevOps
22,113,Luis,Popp,515.124.4567,07-Dec-07,6900.0,108.0,AI Architect
23,114,Den,Raphaely,515.127.4561,07-Dec-02,11000.0,100.0,Lead Developer
24,115,Alexander,Khoo,515.127.4562,18-May-03,3100.0,114.0,Tester
25,116,NaN,NaN,515.127.4563,24-Dec-05,2900.0,114.0,Lead Developer
26,117,Sigal,Tobias,515.127.4564,24-Jul-05,2800.0,114.0,Developer
27,118,Guy,Himuro,515.127.4565,15-Nov-06,2600.0,114.0,AI Developer
28,119,Karen,Colmenares,515.127.4566,10-Aug-07,NaN,114.0,AI Developer
29,120,Matthew,Weiss,650.123.1234,18-Jul-04,8000.0,100.0,DevOps
30,121,Adam,Fripp,650.123.2234,10-Apr-05,8200.0,100.0,DevOps
31,122,Payam,Kaufling,650.123.3234,01-May-03,7900.0,100.0,Developer
32,123,NaN,NaN,650.123.4234,10-Oct-05,6500.0,100.0,AI Developer
33,124,Kevin,Mourgos,650.123.5234,16-Nov-07,5800.0,100.0,AI Developer
34,125,Julia,Nayer,650.124.1214,16-Jul-05,3200.0,120.0,DevOps
35,126,Irene,Mikkilineni,650.124.1224,28-Sep-06,2700.0,120.0,Tester
36,127,James,Landry,650.124.1334,14-Jan-07,2400.0,120.0,Developer
37,128,Steven,Markle,650.124.1434,08-Mar-08,2200.0,NaN,AI Developer
38,129,Laura,Bissot,650.124.5234,20-Aug-05,3300.0,121.0,Developer
39,130,Mozhe,Atkinson,650.124.6234,30-Oct-05,2800.0,121.0,Lead Developer
40,131,NaN,NaN,650.124.7234,16-Feb-05,2500.0,121.0,AI Developer
41,132,TJ,Olson,650.124.8234,10-Apr-07,2100.0,121.0,DevOps
42,133,Jason,Mallin,650.127.1934,14-Jun-04,3300.0,122.0,Developer
43,134,Michael,Rogers,650.127.1834,26-Aug-06,NaN,122.0,Developer
44,135,Ki,Gee,650.127.1734,12-Dec-07,2400.0,122.0,AI Architect
45,136,Hazel,Philtanker,650.127.1634,06-Feb-08,2200.0,122.0,Tester
46,137,Renske,Ladwig,650.121.1234,14-Jul-03,3600.0,123.0,Developer
47,138,NaN,NaN,650.121.2034,26-Oct-05,3200.0,123.0,DevOps
48,139,John,Seo,650.121.2019,12-Feb-06,2700.0,123.0,AI Architect
49,140,Joshua,Patel,650.121.1834,06-Apr-06,2500.0,123.0,Developer

### Level 1 - Understanding the excel data, identifying the missing/incorrect data, connect with Client to validate it

In case, the Client is asking to proceed with the same data

#### Step 1 - Remove duplicate records

In [5]:
emplyees.drop_duplicates(inplace=True) # Remove duplicates and store it in same name
emplyees

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,HIRE_DATE,SALARY,MANAGER_ID,ROLE
0,198,Donald,OConnell,650.507.9833,21-Jun-07,2600.0,124.0,DevOps
1,199,Douglas,Grant,650.507.9844,13-Jan-08,2600.0,124.0,Developer
2,200,Jennifer,Whalen,515.123.4444,17-Sep-03,4400.0,101.0,Tester
3,201,Michael,Hartstein,515.123.5555,17-Feb-04,NaN,100.0,Lead Developer
4,202,Pat,Fay,603.123.6666,17-Aug-05,6000.0,201.0,AI Developer
5,203,NaN,NaN,515.123.7777,07-Jun-02,6500.0,101.0,Developer
6,204,Hermann,Baer,515.123.8888,07-Jun-02,10000.0,101.0,AI Architect
7,205,Shelley,Higgins,515.123.8080,07-Jun-02,12008.0,101.0,Tester
8,206,William,Gietz,515.123.8181,07-Jun-02,8300.0,205.0,DevOps
9,100,Steven,King,515.123.4567,17-Jun-03,24000.0,NaN,Lead Developer
10,101,Neena,Kochhar,515.123.4568,21-Sep-05,17000.0,100.0,AI Developer
11,102,Lex,De Haan,515.123.4569,13-Jan-01,17000.0,100.0,Lead Developer
12,103,Alexander,Hunold,590.423.4567,03-Jan-06,9000.0,102.0,Tester
13,104,Bruce,Ernst,590.423.4568,21-May-07,6000.0,103.0,Developer
14,105,David,Austin,590.423.4569,25-Jun-05,NaN,103.0,AI Architect
15,106,Valli,Pataballa,590.423.4560,05-Feb-06,4800.0,103.0,AI Developer
16,107,NaN,NaN,590.423.5567,07-Feb-07,4200.0,103.0,Developer
17,108,Nancy,Greenberg,515.124.4569,17-Aug-02,12008.0,101.0,Developer
18,109,Daniel,Faviet,515.124.4169,16-Aug-02,9000.0,108.0,AI Architect
19,110,John,Chen,515.124.4269,28-Sep-05,8200.0,108.0,Developer
20,111,Ismael,Sciarra,515.124.4369,30-Sep-05,7700.0,108.0,Developer
21,112,Jose Manuel,Urman,515.124.4469,07-Mar-06,7800.0,108.0,DevOps
22,113,Luis,Popp,515.124.4567,07-Dec-07,6900.0,108.0,AI Architect
23,114,Den,Raphaely,515.127.4561,07-Dec-02,11000.0,100.0,Lead Developer
24,115,Alexander,Khoo,515.127.4562,18-May-03,3100.0,114.0,Tester
25,116,NaN,NaN,515.127.4563,24-Dec-05,2900.0,114.0,Lead Developer
26,117,Sigal,Tobias,515.127.4564,24-Jul-05,2800.0,114.0,Developer
27,118,Guy,Himuro,515.127.4565,15-Nov-06,2600.0,114.0,AI Developer
28,119,Karen,Colmenares,515.127.4566,10-Aug-07,NaN,114.0,AI Developer
29,120,Matthew,Weiss,650.123.1234,18-Jul-04,8000.0,100.0,DevOps
30,121,Adam,Fripp,650.123.2234,10-Apr-05,8200.0,100.0,DevOps
31,122,Payam,Kaufling,650.123.3234,01-May-03,7900.0,100.0,Developer
32,123,NaN,NaN,650.123.4234,10-Oct-05,6500.0,100.0,AI Developer
33,124,Kevin,Mourgos,650.123.5234,16-Nov-07,5800.0,100.0,AI Developer
34,125,Julia,Nayer,650.124.1214,16-Jul-05,3200.0,120.0,DevOps
35,126,Irene,Mikkilineni,650.124.1224,28-Sep-06,2700.0,120.0,Tester
36,127,James,Landry,650.124.1334,14-Jan-07,2400.0,120.0,Developer
37,128,Steven,Markle,650.124.1434,08-Mar-08,2200.0,NaN,AI Developer
38,129,Laura,Bissot,650.124.5234,20-Aug-05,3300.0,121.0,Developer
39,130,Mozhe,Atkinson,650.124.6234,30-Oct-05,2800.0,121.0,Lead Developer
40,131,NaN,NaN,650.124.7234,16-Feb-05,2500.0,121.0,AI Developer
41,132,TJ,Olson,650.124.8234,10-Apr-07,2100.0,121.0,DevOps
42,133,Jason,Mallin,650.127.1934,14-Jun-04,3300.0,122.0,Developer
43,134,Michael,Rogers,650.127.1834,26-Aug-06,NaN,122.0,Developer
44,135,Ki,Gee,650.127.1734,12-Dec-07,2400.0,122.0,AI Architect
45,136,Hazel,Philtanker,650.127.1634,06-Feb-08,2200.0,122.0,Tester
46,137,Renske,Ladwig,650.121.1234,14-Jul-03,3600.0,123.0,Developer
47,138,NaN,NaN,650.121.2034,26-Oct-05,3200.0,123.0,DevOps
48,139,John,Seo,650.121.2019,12-Feb-06,2700.0,123.0,AI Architect
49,140,Joshua,Patel,650.121.1834,06-Apr-06,2500.0,123.0,Developer

#### Step 2: Find out Null records

In [6]:
emplyees.isnull().sum()

EMPLOYEE_ID     0
FIRST_NAME      6
LAST_NAME       6
PHONE_NUMBER    0
HIRE_DATE       0
SALARY          4
MANAGER_ID      2
ROLE            0
dtype: int64

#### Step 3 - Record a document

* Client gave 49 records out of which 16 records are removed because those records do not have complete information

In [7]:
emplyees.dropna(inplace=True)
emplyees

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,HIRE_DATE,SALARY,MANAGER_ID,ROLE
0,198,Donald,OConnell,650.507.9833,21-Jun-07,2600.0,124.0,DevOps
1,199,Douglas,Grant,650.507.9844,13-Jan-08,2600.0,124.0,Developer
2,200,Jennifer,Whalen,515.123.4444,17-Sep-03,4400.0,101.0,Tester
4,202,Pat,Fay,603.123.6666,17-Aug-05,6000.0,201.0,AI Developer
6,204,Hermann,Baer,515.123.8888,07-Jun-02,10000.0,101.0,AI Architect
7,205,Shelley,Higgins,515.123.8080,07-Jun-02,12008.0,101.0,Tester
8,206,William,Gietz,515.123.8181,07-Jun-02,8300.0,205.0,DevOps
10,101,Neena,Kochhar,515.123.4568,21-Sep-05,17000.0,100.0,AI Developer
11,102,Lex,De Haan,515.123.4569,13-Jan-01,17000.0,100.0,Lead Developer
12,103,Alexander,Hunold,590.423.4567,03-Jan-06,9000.0,102.0,Tester
13,104,Bruce,Ernst,590.423.4568,21-May-07,6000.0,103.0,Developer
15,106,Valli,Pataballa,590.423.4560,05-Feb-06,4800.0,103.0,AI Developer
17,108,Nancy,Greenberg,515.124.4569,17-Aug-02,12008.0,101.0,Developer
18,109,Daniel,Faviet,515.124.4169,16-Aug-02,9000.0,108.0,AI Architect
19,110,John,Chen,515.124.4269,28-Sep-05,8200.0,108.0,Developer
20,111,Ismael,Sciarra,515.124.4369,30-Sep-05,7700.0,108.0,Developer
21,112,Jose Manuel,Urman,515.124.4469,07-Mar-06,7800.0,108.0,DevOps
22,113,Luis,Popp,515.124.4567,07-Dec-07,6900.0,108.0,AI Architect
23,114,Den,Raphaely,515.127.4561,07-Dec-02,11000.0,100.0,Lead Developer
24,115,Alexander,Khoo,515.127.4562,18-May-03,3100.0,114.0,Tester
26,117,Sigal,Tobias,515.127.4564,24-Jul-05,2800.0,114.0,Developer
27,118,Guy,Himuro,515.127.4565,15-Nov-06,2600.0,114.0,AI Developer
29,120,Matthew,Weiss,650.123.1234,18-Jul-04,8000.0,100.0,DevOps
30,121,Adam,Fripp,650.123.2234,10-Apr-05,8200.0,100.0,DevOps
31,122,Payam,Kaufling,650.123.3234,01-May-03,7900.0,100.0,Developer
33,124,Kevin,Mourgos,650.123.5234,16-Nov-07,5800.0,100.0,AI Developer
34,125,Julia,Nayer,650.124.1214,16-Jul-05,3200.0,120.0,DevOps
35,126,Irene,Mikkilineni,650.124.1224,28-Sep-06,2700.0,120.0,Tester
36,127,James,Landry,650.124.1334,14-Jan-07,2400.0,120.0,Developer
38,129,Laura,Bissot,650.124.5234,20-Aug-05,3300.0,121.0,Developer
39,130,Mozhe,Atkinson,650.124.6234,30-Oct-05,2800.0,121.0,Lead Developer
41,132,TJ,Olson,650.124.8234,10-Apr-07,2100.0,121.0,DevOps
42,133,Jason,Mallin,650.127.1934,14-Jun-04,3300.0,122.0,Developer
44,135,Ki,Gee,650.127.1734,12-Dec-07,2400.0,122.0,AI Architect
45,136,Hazel,Philtanker,650.127.1634,06-Feb-08,2200.0,122.0,Tester
46,137,Renske,Ladwig,650.121.1234,14-Jul-03,3600.0,123.0,Developer
48,139,John,Seo,650.121.2019,12-Feb-06,2700.0,123.0,AI Architect
49,140,Joshua,Patel,650.121.1834,06-Apr-06,2500.0,123.0,Developer

In [8]:
emplyees.shape

(38, 8)

#### Step 4: Get Approval
* Send this to Client and get the approval to proceed for Model Building or Training

In [9]:
emplyees.isnull().sum()

EMPLOYEE_ID     0
FIRST_NAME      0
LAST_NAME       0
PHONE_NUMBER    0
HIRE_DATE       0
SALARY          0
MANAGER_ID      0
ROLE            0
dtype: int64

## Level 2 - Data Cleaning

In [10]:
employee_data=pd.read_csv("employees.csv")
employee_data

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,HIRE_DATE,SALARY,MANAGER_ID,ROLE
0,198,Donald,OConnell,650.507.9833,21-Jun-07,2600.0,124.0,DevOps
1,199,Douglas,Grant,650.507.9844,13-Jan-08,2600.0,124.0,Developer
2,200,Jennifer,Whalen,515.123.4444,17-Sep-03,4400.0,101.0,Tester
3,201,Michael,Hartstein,515.123.5555,17-Feb-04,NaN,100.0,Lead Developer
4,202,Pat,Fay,603.123.6666,17-Aug-05,6000.0,201.0,AI Developer
5,203,NaN,NaN,515.123.7777,07-Jun-02,6500.0,101.0,Developer
6,204,Hermann,Baer,515.123.8888,07-Jun-02,10000.0,101.0,AI Architect
7,205,Shelley,Higgins,515.123.8080,07-Jun-02,12008.0,101.0,Tester
8,206,William,Gietz,515.123.8181,07-Jun-02,8300.0,205.0,DevOps
9,100,Steven,King,515.123.4567,17-Jun-03,24000.0,NaN,Lead Developer
10,101,Neena,Kochhar,515.123.4568,21-Sep-05,17000.0,100.0,AI Developer
11,102,Lex,De Haan,515.123.4569,13-Jan-01,17000.0,100.0,Lead Developer
12,103,Alexander,Hunold,590.423.4567,03-Jan-06,9000.0,102.0,Tester
13,104,Bruce,Ernst,590.423.4568,21-May-07,6000.0,103.0,Developer
14,105,David,Austin,590.423.4569,25-Jun-05,NaN,103.0,AI Architect
15,106,Valli,Pataballa,590.423.4560,05-Feb-06,4800.0,103.0,AI Developer
16,107,NaN,NaN,590.423.5567,07-Feb-07,4200.0,103.0,Developer
17,108,Nancy,Greenberg,515.124.4569,17-Aug-02,12008.0,101.0,Developer
18,109,Daniel,Faviet,515.124.4169,16-Aug-02,9000.0,108.0,AI Architect
19,110,John,Chen,515.124.4269,28-Sep-05,8200.0,108.0,Developer
20,111,Ismael,Sciarra,515.124.4369,30-Sep-05,7700.0,108.0,Developer
21,112,Jose Manuel,Urman,515.124.4469,07-Mar-06,7800.0,108.0,DevOps
22,113,Luis,Popp,515.124.4567,07-Dec-07,6900.0,108.0,AI Architect
23,114,Den,Raphaely,515.127.4561,07-Dec-02,11000.0,100.0,Lead Developer
24,115,Alexander,Khoo,515.127.4562,18-May-03,3100.0,114.0,Tester
25,116,NaN,NaN,515.127.4563,24-Dec-05,2900.0,114.0,Lead Developer
26,117,Sigal,Tobias,515.127.4564,24-Jul-05,2800.0,114.0,Developer
27,118,Guy,Himuro,515.127.4565,15-Nov-06,2600.0,114.0,AI Developer
28,119,Karen,Colmenares,515.127.4566,10-Aug-07,NaN,114.0,AI Developer
29,120,Matthew,Weiss,650.123.1234,18-Jul-04,8000.0,100.0,DevOps
30,121,Adam,Fripp,650.123.2234,10-Apr-05,8200.0,100.0,DevOps
31,122,Payam,Kaufling,650.123.3234,01-May-03,7900.0,100.0,Developer
32,123,NaN,NaN,650.123.4234,10-Oct-05,6500.0,100.0,AI Developer
33,124,Kevin,Mourgos,650.123.5234,16-Nov-07,5800.0,100.0,AI Developer
34,125,Julia,Nayer,650.124.1214,16-Jul-05,3200.0,120.0,DevOps
35,126,Irene,Mikkilineni,650.124.1224,28-Sep-06,2700.0,120.0,Tester
36,127,James,Landry,650.124.1334,14-Jan-07,2400.0,120.0,Developer
37,128,Steven,Markle,650.124.1434,08-Mar-08,2200.0,NaN,AI Developer
38,129,Laura,Bissot,650.124.5234,20-Aug-05,3300.0,121.0,Developer
39,130,Mozhe,Atkinson,650.124.6234,30-Oct-05,2800.0,121.0,Lead Developer
40,131,NaN,NaN,650.124.7234,16-Feb-05,2500.0,121.0,AI Developer
41,132,TJ,Olson,650.124.8234,10-Apr-07,2100.0,121.0,DevOps
42,133,Jason,Mallin,650.127.1934,14-Jun-04,3300.0,122.0,Developer
43,134,Michael,Rogers,650.127.1834,26-Aug-06,NaN,122.0,Developer
44,135,Ki,Gee,650.127.1734,12-Dec-07,2400.0,122.0,AI Architect
45,136,Hazel,Philtanker,650.127.1634,06-Feb-08,2200.0,122.0,Tester
46,137,Renske,Ladwig,650.121.1234,14-Jul-03,3600.0,123.0,Developer
47,138,NaN,NaN,650.121.2034,26-Oct-05,3200.0,123.0,DevOps
48,139,John,Seo,650.121.2019,12-Feb-06,2700.0,123.0,AI Architect
49,140,Joshua,Patel,650.121.1834,06-Apr-06,2500.0,123.0,Developer

In [11]:
employee_data.duplicated() # Find out the duplicate entries

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

#### Step 4.1 Drop / Remove the duplicate entries

In [12]:
employee_data.drop_duplicates(inplace=True)
employee_data

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,HIRE_DATE,SALARY,MANAGER_ID,ROLE
0,198,Donald,OConnell,650.507.9833,21-Jun-07,2600.0,124.0,DevOps
1,199,Douglas,Grant,650.507.9844,13-Jan-08,2600.0,124.0,Developer
2,200,Jennifer,Whalen,515.123.4444,17-Sep-03,4400.0,101.0,Tester
3,201,Michael,Hartstein,515.123.5555,17-Feb-04,NaN,100.0,Lead Developer
4,202,Pat,Fay,603.123.6666,17-Aug-05,6000.0,201.0,AI Developer
5,203,NaN,NaN,515.123.7777,07-Jun-02,6500.0,101.0,Developer
6,204,Hermann,Baer,515.123.8888,07-Jun-02,10000.0,101.0,AI Architect
7,205,Shelley,Higgins,515.123.8080,07-Jun-02,12008.0,101.0,Tester
8,206,William,Gietz,515.123.8181,07-Jun-02,8300.0,205.0,DevOps
9,100,Steven,King,515.123.4567,17-Jun-03,24000.0,NaN,Lead Developer
10,101,Neena,Kochhar,515.123.4568,21-Sep-05,17000.0,100.0,AI Developer
11,102,Lex,De Haan,515.123.4569,13-Jan-01,17000.0,100.0,Lead Developer
12,103,Alexander,Hunold,590.423.4567,03-Jan-06,9000.0,102.0,Tester
13,104,Bruce,Ernst,590.423.4568,21-May-07,6000.0,103.0,Developer
14,105,David,Austin,590.423.4569,25-Jun-05,NaN,103.0,AI Architect
15,106,Valli,Pataballa,590.423.4560,05-Feb-06,4800.0,103.0,AI Developer
16,107,NaN,NaN,590.423.5567,07-Feb-07,4200.0,103.0,Developer
17,108,Nancy,Greenberg,515.124.4569,17-Aug-02,12008.0,101.0,Developer
18,109,Daniel,Faviet,515.124.4169,16-Aug-02,9000.0,108.0,AI Architect
19,110,John,Chen,515.124.4269,28-Sep-05,8200.0,108.0,Developer
20,111,Ismael,Sciarra,515.124.4369,30-Sep-05,7700.0,108.0,Developer
21,112,Jose Manuel,Urman,515.124.4469,07-Mar-06,7800.0,108.0,DevOps
22,113,Luis,Popp,515.124.4567,07-Dec-07,6900.0,108.0,AI Architect
23,114,Den,Raphaely,515.127.4561,07-Dec-02,11000.0,100.0,Lead Developer
24,115,Alexander,Khoo,515.127.4562,18-May-03,3100.0,114.0,Tester
25,116,NaN,NaN,515.127.4563,24-Dec-05,2900.0,114.0,Lead Developer
26,117,Sigal,Tobias,515.127.4564,24-Jul-05,2800.0,114.0,Developer
27,118,Guy,Himuro,515.127.4565,15-Nov-06,2600.0,114.0,AI Developer
28,119,Karen,Colmenares,515.127.4566,10-Aug-07,NaN,114.0,AI Developer
29,120,Matthew,Weiss,650.123.1234,18-Jul-04,8000.0,100.0,DevOps
30,121,Adam,Fripp,650.123.2234,10-Apr-05,8200.0,100.0,DevOps
31,122,Payam,Kaufling,650.123.3234,01-May-03,7900.0,100.0,Developer
32,123,NaN,NaN,650.123.4234,10-Oct-05,6500.0,100.0,AI Developer
33,124,Kevin,Mourgos,650.123.5234,16-Nov-07,5800.0,100.0,AI Developer
34,125,Julia,Nayer,650.124.1214,16-Jul-05,3200.0,120.0,DevOps
35,126,Irene,Mikkilineni,650.124.1224,28-Sep-06,2700.0,120.0,Tester
36,127,James,Landry,650.124.1334,14-Jan-07,2400.0,120.0,Developer
37,128,Steven,Markle,650.124.1434,08-Mar-08,2200.0,NaN,AI Developer
38,129,Laura,Bissot,650.124.5234,20-Aug-05,3300.0,121.0,Developer
39,130,Mozhe,Atkinson,650.124.6234,30-Oct-05,2800.0,121.0,Lead Developer
40,131,NaN,NaN,650.124.7234,16-Feb-05,2500.0,121.0,AI Developer
41,132,TJ,Olson,650.124.8234,10-Apr-07,2100.0,121.0,DevOps
42,133,Jason,Mallin,650.127.1934,14-Jun-04,3300.0,122.0,Developer
43,134,Michael,Rogers,650.127.1834,26-Aug-06,NaN,122.0,Developer
44,135,Ki,Gee,650.127.1734,12-Dec-07,2400.0,122.0,AI Architect
45,136,Hazel,Philtanker,650.127.1634,06-Feb-08,2200.0,122.0,Tester
46,137,Renske,Ladwig,650.121.1234,14-Jul-03,3600.0,123.0,Developer
47,138,NaN,NaN,650.121.2034,26-Oct-05,3200.0,123.0,DevOps
48,139,John,Seo,650.121.2019,12-Feb-06,2700.0,123.0,AI Architect
49,140,Joshua,Patel,650.121.1834,06-Apr-06,2500.0,123.0,Developer

#### Step 4.2 - Identify the Null entries

In [13]:
employee_data.isna().sum()

EMPLOYEE_ID     0
FIRST_NAME      6
LAST_NAME       6
PHONE_NUMBER    0
HIRE_DATE       0
SALARY          4
MANAGER_ID      2
ROLE            0
dtype: int64

#### Step 4.3 - Go for best Imputation

In [14]:
employee_data["ROLE"].unique()

array(['DevOps', 'Developer', 'Tester', 'Lead Developer', 'AI Developer',
       'AI Architect'], dtype=object)

##### 4.3.1 Data Analtstics

In [15]:
employee_data[employee_data["ROLE"] == "DevOps"]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,HIRE_DATE,SALARY,MANAGER_ID,ROLE
0,198,Donald,OConnell,650.507.9833,21-Jun-07,2600.0,124.0,DevOps
8,206,William,Gietz,515.123.8181,07-Jun-02,8300.0,205.0,DevOps
21,112,Jose Manuel,Urman,515.124.4469,07-Mar-06,7800.0,108.0,DevOps
29,120,Matthew,Weiss,650.123.1234,18-Jul-04,8000.0,100.0,DevOps
30,121,Adam,Fripp,650.123.2234,10-Apr-05,8200.0,100.0,DevOps
34,125,Julia,Nayer,650.124.1214,16-Jul-05,3200.0,120.0,DevOps
41,132,TJ,Olson,650.124.8234,10-Apr-07,2100.0,121.0,DevOps
47,138,NaN,NaN,650.121.2034,26-Oct-05,3200.0,123.0,DevOps

In [16]:
employee_data[employee_data["ROLE"] == "Developer"]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,HIRE_DATE,SALARY,MANAGER_ID,ROLE
1,199,Douglas,Grant,650.507.9844,13-Jan-08,2600.0,124.0,Developer
5,203,NaN,NaN,515.123.7777,07-Jun-02,6500.0,101.0,Developer
13,104,Bruce,Ernst,590.423.4568,21-May-07,6000.0,103.0,Developer
16,107,NaN,NaN,590.423.5567,07-Feb-07,4200.0,103.0,Developer
17,108,Nancy,Greenberg,515.124.4569,17-Aug-02,12008.0,101.0,Developer
19,110,John,Chen,515.124.4269,28-Sep-05,8200.0,108.0,Developer
20,111,Ismael,Sciarra,515.124.4369,30-Sep-05,7700.0,108.0,Developer
26,117,Sigal,Tobias,515.127.4564,24-Jul-05,2800.0,114.0,Developer
31,122,Payam,Kaufling,650.123.3234,01-May-03,7900.0,100.0,Developer
36,127,James,Landry,650.124.1334,14-Jan-07,2400.0,120.0,Developer
38,129,Laura,Bissot,650.124.5234,20-Aug-05,3300.0,121.0,Developer
42,133,Jason,Mallin,650.127.1934,14-Jun-04,3300.0,122.0,Developer
43,134,Michael,Rogers,650.127.1834,26-Aug-06,NaN,122.0,Developer
46,137,Renske,Ladwig,650.121.1234,14-Jul-03,3600.0,123.0,Developer
49,140,Joshua,Patel,650.121.1834,06-Apr-06,2500.0,123.0,Developer

In [17]:
employee_data[employee_data["ROLE"] == "Tester"]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,HIRE_DATE,SALARY,MANAGER_ID,ROLE
2,200,Jennifer,Whalen,515.123.4444,17-Sep-03,4400.0,101.0,Tester
7,205,Shelley,Higgins,515.123.8080,07-Jun-02,12008.0,101.0,Tester
12,103,Alexander,Hunold,590.423.4567,03-Jan-06,9000.0,102.0,Tester
24,115,Alexander,Khoo,515.127.4562,18-May-03,3100.0,114.0,Tester
35,126,Irene,Mikkilineni,650.124.1224,28-Sep-06,2700.0,120.0,Tester
45,136,Hazel,Philtanker,650.127.1634,06-Feb-08,2200.0,122.0,Tester

In [18]:
employee_data[employee_data["ROLE"] == "Lead Developer"]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,HIRE_DATE,SALARY,MANAGER_ID,ROLE
3,201,Michael,Hartstein,515.123.5555,17-Feb-04,NaN,100.0,Lead Developer
9,100,Steven,King,515.123.4567,17-Jun-03,24000.0,NaN,Lead Developer
11,102,Lex,De Haan,515.123.4569,13-Jan-01,17000.0,100.0,Lead Developer
23,114,Den,Raphaely,515.127.4561,07-Dec-02,11000.0,100.0,Lead Developer
25,116,NaN,NaN,515.127.4563,24-Dec-05,2900.0,114.0,Lead Developer
39,130,Mozhe,Atkinson,650.124.6234,30-Oct-05,2800.0,121.0,Lead Developer

In [19]:
employee_data[employee_data["ROLE"] == "AI Developer"]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,HIRE_DATE,SALARY,MANAGER_ID,ROLE
4,202,Pat,Fay,603.123.6666,17-Aug-05,6000.0,201.0,AI Developer
10,101,Neena,Kochhar,515.123.4568,21-Sep-05,17000.0,100.0,AI Developer
15,106,Valli,Pataballa,590.423.4560,05-Feb-06,4800.0,103.0,AI Developer
27,118,Guy,Himuro,515.127.4565,15-Nov-06,2600.0,114.0,AI Developer
28,119,Karen,Colmenares,515.127.4566,10-Aug-07,NaN,114.0,AI Developer
32,123,NaN,NaN,650.123.4234,10-Oct-05,6500.0,100.0,AI Developer
33,124,Kevin,Mourgos,650.123.5234,16-Nov-07,5800.0,100.0,AI Developer
37,128,Steven,Markle,650.124.1434,08-Mar-08,2200.0,NaN,AI Developer
40,131,NaN,NaN,650.124.7234,16-Feb-05,2500.0,121.0,AI Developer

In [20]:
employee_data[employee_data["ROLE"] == "AI Architect"]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,HIRE_DATE,SALARY,MANAGER_ID,ROLE
6,204,Hermann,Baer,515.123.8888,07-Jun-02,10000.0,101.0,AI Architect
14,105,David,Austin,590.423.4569,25-Jun-05,NaN,103.0,AI Architect
18,109,Daniel,Faviet,515.124.4169,16-Aug-02,9000.0,108.0,AI Architect
22,113,Luis,Popp,515.124.4567,07-Dec-07,6900.0,108.0,AI Architect
44,135,Ki,Gee,650.127.1734,12-Dec-07,2400.0,122.0,AI Architect
48,139,John,Seo,650.121.2019,12-Feb-06,2700.0,123.0,AI Architect

#### Data Analytics Task
1. Impute the relevant values in the Salary Coulmn whether it is NaN, based on Department Filtering.
2. Impute the relevant ages

In [21]:
employee_data[(employee_data["ROLE"] == "AI Architect") & (employee_data["SALARY"].isna())]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,HIRE_DATE,SALARY,MANAGER_ID,ROLE
14,105,David,Austin,590.423.4569,25-Jun-05,NaN,103.0,AI Architect

In [36]:
employee_105 = employee_data[(employee_data["EMPLOYEE_ID"]) == 105]
employee_105

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,HIRE_DATE,SALARY,MANAGER_ID,ROLE
14,105,David,Austin,590.423.4569,25-Jun-05,NaN,103.0,AI Architect

In [31]:
employee_105["SALARY"] = employee_105["SALARY"].fillna(9999)

employee_105

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_26984\2753165524.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  employee_105["SALARY"] = employee_105["SALARY"].fillna(9999)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,HIRE_DATE,SALARY,MANAGER_ID,ROLE
14,9999,9999,9999,9999,9999,9999.0,9999.0,9999

In [39]:
employee_105.loc[employee_105["SALARY"].isnull(), "SALARY"] = (
    employee_105.loc[employee_105["SALARY"].isnull(), "SALARY"].fillna(9999)
)

employee_105

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,HIRE_DATE,SALARY,MANAGER_ID,ROLE
14,105,David,Austin,590.423.4569,25-Jun-05,9999.0,103.0,AI Architect